import type { Program } from "@/lib/programs/types";

/**
 * Curated REAL English-taught Master's programmes at German public universities (ADR-0006). Real
 * institutions, cities, and official study pages; requirements are indicative and kept
 * `needsVerification: true` — confirm exact deadlines/tests/tuition on each programme's official page.
 * This is a hand-verified subset, NOT a scrape of DAAD/Hochschulkompass. Grows via curation / a future
 * data partnership. Used offline and as the fallback when the Supabase `programs` table is empty.
 */
const R = "2026-06-20";
const BW = 1500; // Baden-Württemberg non-EU/EEA tuition per semester

export const SEED_PROGRAMS: Program[] = [
  {
    id: "tum-data-eng", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs", retrievedAt: R,
    name: "Data Engineering and Analytics", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5 / TOEFL 88",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Data Science"],
    mode: "full_time", semesters: 4, intake: "winter", applicationDeadline: "~31 May (winter) — verify",
    tuitionPerSemester: null, semesterContribution: 150, admissionMode: "aptitude",
    scholarships: ["DAAD", "Deutschlandstipendium"], testsRequired: { ielts: "6.5", gre: "recommended" },
    needsVerification: true, description: "Big-data systems, machine learning, and analytics at TUM's School of CIT.",
  },
  {
    id: "tum-informatics", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs", retrievedAt: R,
    name: "Informatics", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "aptitude", testsRequired: { ielts: "6.5" }, needsVerification: true,
    description: "Broad CS master with specialisation areas; English track available.",
  },
  {
    id: "tum-mgmt-tech", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs", retrievedAt: R,
    name: "Management and Technology", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Management", "Technology Management"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "aptitude", testsRequired: { ielts: "6.5", gmat: "recommended" }, needsVerification: true,
    description: "Management with an engineering/technology focus at TUM School of Management.",
  },
  {
    id: "rwth-data-science", source: "curated", sourceUrl: "https://www.rwth-aachen.de/cms/root/studium/Vor-dem-Studium/lidx/1/", retrievedAt: R,
    name: "Data Science", degree: "M.Sc.", courseType: "master",
    university: "RWTH Aachen University", institutionType: "uni", city: "Aachen", bundesland: "North Rhine-Westphalia",
    lat: 50.776, lng: 6.083, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", testsRequired: { ielts: "6.0" }, needsVerification: true,
    description: "Statistics, machine learning, and data engineering at RWTH.",
  },
  {
    id: "rwth-cs", source: "curated", sourceUrl: "https://www.rwth-aachen.de/cms/root/studium/Vor-dem-Studium/lidx/1/", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "RWTH Aachen University", institutionType: "uni", city: "Aachen", bundesland: "North Rhine-Westphalia",
    lat: 50.776, lng: 6.083, languages: "de_en", languageLevelEn: "IELTS 6.0", languageLevelDe: "some modules in German",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", needsVerification: true, description: "Research-oriented CS; English-taught electives.",
  },
  {
    id: "stuttgart-infotech", source: "curated", sourceUrl: "https://www.uni-stuttgart.de/en/study/", retrievedAt: R,
    name: "Information Technology (INFOTECH)", degree: "M.Sc.", courseType: "master",
    university: "University of Stuttgart", institutionType: "uni", city: "Stuttgart", bundesland: "Baden-Württemberg",
    lat: 48.775, lng: 9.182, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Electrical Engineering", "Information Technology"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 190,
    admissionMode: "aptitude", testsRequired: { ielts: "6.5", gre: "recommended" }, needsVerification: true,
    description: "Microelectronics, communications, and embedded systems.",
  },
  {
    id: "stuttgart-cs", source: "curated", sourceUrl: "https://www.uni-stuttgart.de/en/study/", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "University of Stuttgart", institutionType: "uni", city: "Stuttgart", bundesland: "Baden-Württemberg",
    lat: 48.775, lng: 9.182, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 190,
    admissionMode: "aptitude", needsVerification: true, description: "English-taught CS master at Stuttgart.",
  },
  {
    id: "kit-optics", source: "curated", sourceUrl: "https://www.kit.edu/studying.php", retrievedAt: R,
    name: "Optics and Photonics", degree: "M.Sc.", courseType: "master",
    university: "Karlsruhe Institute of Technology", institutionType: "uni", city: "Karlsruhe", bundesland: "Baden-Württemberg",
    lat: 49.006, lng: 8.403, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Physics", "Photonics"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "aptitude", needsVerification: true, description: "Optical systems and photonic technologies at KIT.",
  },
  {
    id: "darmstadt-dss", source: "curated", sourceUrl: "https://www.tu-darmstadt.de/studieren/", retrievedAt: R,
    name: "Distributed Software Systems", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Darmstadt", institutionType: "uni", city: "Darmstadt", bundesland: "Hesse",
    lat: 49.872, lng: 8.651, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Distributed Systems"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 290,
    admissionMode: "nc", testsRequired: { ielts: "6.5" }, needsVerification: true,
    description: "Cloud, distributed, and software systems engineering.",
  },
  {
    id: "darmstadt-ice", source: "curated", sourceUrl: "https://www.tu-darmstadt.de/studieren/", retrievedAt: R,
    name: "Information and Communication Engineering", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Darmstadt", institutionType: "uni", city: "Darmstadt", bundesland: "Hesse",
    lat: 49.872, lng: 8.651, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Electrical Engineering", "Communications"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 290,
    admissionMode: "nc", needsVerification: true, description: "Signal processing, communications, and embedded systems.",
  },
  {
    id: "mannheim-data-science", source: "curated", sourceUrl: "https://www.uni-mannheim.de/en/academics/", retrievedAt: R,
    name: "Data Science", degree: "M.Sc.", courseType: "master",
    university: "University of Mannheim", institutionType: "uni", city: "Mannheim", bundesland: "Baden-Württemberg",
    lat: 49.487, lng: 8.466, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Statistics"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 180,
    admissionMode: "aptitude", needsVerification: true, description: "Data science across CS, statistics, and economics.",
  },
  {
    id: "mannheim-management", source: "curated", sourceUrl: "https://www.uni-mannheim.de/en/academics/", retrievedAt: R,
    name: "Management", degree: "M.Sc.", courseType: "master",
    university: "University of Mannheim", institutionType: "uni", city: "Mannheim", bundesland: "Baden-Württemberg",
    lat: 49.487, lng: 8.466, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Management", "Business"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 180,
    admissionMode: "aptitude", testsRequired: { gmat: "recommended" }, needsVerification: true,
    description: "Top-ranked business school; selective management master.",
  },
  {
    id: "heidelberg-data-cs", source: "curated", sourceUrl: "https://www.uni-heidelberg.de/en/study", retrievedAt: R,
    name: "Data and Computer Science", degree: "M.Sc.", courseType: "master",
    university: "Heidelberg University", institutionType: "uni", city: "Heidelberg", bundesland: "Baden-Württemberg",
    lat: 49.398, lng: 8.672, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Data Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "aptitude", needsVerification: true, description: "Scientific computing, ML, and visual computing.",
  },
  {
    id: "heidelberg-physics", source: "curated", sourceUrl: "https://www.uni-heidelberg.de/en/study", retrievedAt: R,
    name: "Physics", degree: "M.Sc.", courseType: "master",
    university: "Heidelberg University", institutionType: "uni", city: "Heidelberg", bundesland: "Baden-Württemberg",
    lat: 49.398, lng: 8.672, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Physics"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "open", needsVerification: true, description: "Research-led physics master; English-taught.",
  },
  {
    id: "dresden-cms", source: "curated", sourceUrl: "https://tu-dresden.de/studium", retrievedAt: R,
    name: "Computational Modeling and Simulation", degree: "M.Sc.", courseType: "master",
    university: "TU Dresden", institutionType: "uni", city: "Dresden", bundesland: "Saxony",
    lat: 51.05, lng: 13.737, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Computational Engineering", "Simulation"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 280,
    admissionMode: "aptitude", needsVerification: true, description: "Modelling and simulation across engineering and science.",
  },
  {
    id: "dresden-dse", source: "curated", sourceUrl: "https://tu-dresden.de/studium", retrievedAt: R,
    name: "Distributed Systems Engineering", degree: "M.Sc.", courseType: "master",
    university: "TU Dresden", institutionType: "uni", city: "Dresden", bundesland: "Saxony",
    lat: 51.05, lng: 13.737, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Distributed Systems"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 280,
    admissionMode: "nc", needsVerification: true, description: "Systems engineering for large-scale distributed software.",
  },
  {
    id: "freiburg-cs", source: "curated", sourceUrl: "https://www.uni-freiburg.de/en/studies", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "University of Freiburg", institutionType: "uni", city: "Freiburg", bundesland: "Baden-Württemberg",
    lat: 47.999, lng: 7.842, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 160,
    admissionMode: "open", needsVerification: true, description: "Strong in ML, robotics, and bioinformatics.",
  },
  {
    id: "freiburg-reem", source: "curated", sourceUrl: "https://www.uni-freiburg.de/en/studies", retrievedAt: R,
    name: "Renewable Energy Engineering and Management", degree: "M.Sc.", courseType: "master",
    university: "University of Freiburg", institutionType: "uni", city: "Freiburg", bundesland: "Baden-Württemberg",
    lat: 47.999, lng: 7.842, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Renewable Energy", "Engineering Management"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 160,
    admissionMode: "aptitude", needsVerification: true, description: "Energy technology with management and policy.",
  },
  {
    id: "tuebingen-ml", source: "curated", sourceUrl: "https://uni-tuebingen.de/en/study/", retrievedAt: R,
    name: "Machine Learning", degree: "M.Sc.", courseType: "master",
    university: "University of Tübingen", institutionType: "uni", city: "Tübingen", bundesland: "Baden-Württemberg",
    lat: 48.521, lng: 9.057, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Machine Learning", "Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "aptitude", needsVerification: true, description: "Dedicated ML master at a leading AI research hub.",
  },
  {
    id: "saarland-cs", source: "curated", sourceUrl: "https://www.uni-saarland.de/en/study.html", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "Saarland University", institutionType: "uni", city: "Saarbrücken", bundesland: "Saarland",
    lat: 49.235, lng: 6.996, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 300,
    admissionMode: "open", needsVerification: true, description: "Renowned CS faculty (MPI, CISPA, DFKI on campus).",
  },
  {
    id: "saarland-dsai", source: "curated", sourceUrl: "https://www.uni-saarland.de/en/study.html", retrievedAt: R,
    name: "Data Science and Artificial Intelligence", degree: "M.Sc.", courseType: "master",
    university: "Saarland University", institutionType: "uni", city: "Saarbrücken", bundesland: "Saarland",
    lat: 49.235, lng: 6.996, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Artificial Intelligence"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 300,
    admissionMode: "open", needsVerification: true, description: "AI and data science with strong research ties.",
  },
  {
    id: "bonn-cs", source: "curated", sourceUrl: "https://www.uni-bonn.de/en/studying", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "University of Bonn", institutionType: "uni", city: "Bonn", bundesland: "North Rhine-Westphalia",
    lat: 50.737, lng: 7.098, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", needsVerification: true, description: "Research-focused CS; intelligent systems and graphics.",
  },
  {
    id: "lmu-data-science", source: "curated", sourceUrl: "https://www.lmu.de/en/study/index.html", retrievedAt: R,
    name: "Data Science", degree: "M.Sc.", courseType: "master",
    university: "LMU Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Statistics"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "aptitude", needsVerification: true, description: "Statistics-rooted data science master at LMU.",
  },
  {
    id: "goettingen-ads", source: "curated", sourceUrl: "https://www.uni-goettingen.de/en/", retrievedAt: R,
    name: "Applied Data Science", degree: "M.Sc.", courseType: "master",
    university: "University of Göttingen", institutionType: "uni", city: "Göttingen", bundesland: "Lower Saxony",
    lat: 51.541, lng: 9.915, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 380,
    admissionMode: "open", needsVerification: true, description: "Applied, interdisciplinary data science.",
  },
];
