import type { Program } from "@/lib/programs/types";
import { TUITION_BW_EUR } from "@/lib/facts";

/**
 * Curated REAL English-taught Master's programmes at German public universities (ADR-0006). Real
 * institutions, cities, and official study pages; requirements are indicative and kept
 * `needsVerification: true` — confirm exact deadlines/tests/tuition on each programme's official page.
 * This is a hand-verified subset, NOT a scrape of DAAD/Hochschulkompass. Grows via curation / a future
 * data partnership. Used offline and as the fallback when the Supabase `programs` table is empty.
 */
const R = "2026-06-20";
const BW = TUITION_BW_EUR; // Baden-Württemberg non-EU/EEA tuition per semester

export const SEED_PROGRAMS: Program[] = [
  {
    id: "tum-data-eng", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs", retrievedAt: R,
    name: "Data Engineering and Analytics", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5 / TOEFL 88",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Data Science"],
    mode: "full_time", semesters: 4, intake: "winter", applicationDeadline: "~31 May (winter) — verify",
    tuitionPerSemester: null, semesterContribution: 150, admissionMode: "aptitude",
    scholarships: ["DAAD", "Deutschlandstipendium"], testsRequired: { ielts: "6.5", gre: "recommended" },
    needsVerification: true, description: "Big-data systems, machine learning, and analytics at TUM's School of CIT.",
  },
  {
    id: "tum-informatics", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs", retrievedAt: R,
    name: "Informatics", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "aptitude", testsRequired: { ielts: "6.5" }, needsVerification: true,
    description: "Broad CS master with specialisation areas; English track available.",
  },
  {
    id: "tum-mgmt-tech", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs", retrievedAt: R,
    name: "Management and Technology", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Management", "Technology Management"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "aptitude", testsRequired: { ielts: "6.5", gmat: "recommended" }, needsVerification: true,
    description: "Management with an engineering/technology focus at TUM School of Management.",
  },
  {
    id: "rwth-data-science", source: "curated", sourceUrl: "https://www.rwth-aachen.de/cms/root/studium/Vor-dem-Studium/lidx/1/", retrievedAt: R,
    name: "Data Science", degree: "M.Sc.", courseType: "master",
    university: "RWTH Aachen University", institutionType: "uni", city: "Aachen", bundesland: "North Rhine-Westphalia",
    lat: 50.776, lng: 6.083, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", testsRequired: { ielts: "6.0" }, needsVerification: true,
    description: "Statistics, machine learning, and data engineering at RWTH.",
  },
  {
    id: "rwth-cs", source: "curated", sourceUrl: "https://www.rwth-aachen.de/cms/root/studium/Vor-dem-Studium/lidx/1/", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "RWTH Aachen University", institutionType: "uni", city: "Aachen", bundesland: "North Rhine-Westphalia",
    lat: 50.776, lng: 6.083, languages: "de_en", languageLevelEn: "IELTS 6.0", languageLevelDe: "some modules in German",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", needsVerification: true, description: "Research-oriented CS; English-taught electives.",
  },
  {
    id: "stuttgart-infotech", source: "curated", sourceUrl: "https://www.uni-stuttgart.de/en/study/", retrievedAt: R,
    name: "Information Technology (INFOTECH)", degree: "M.Sc.", courseType: "master",
    university: "University of Stuttgart", institutionType: "uni", city: "Stuttgart", bundesland: "Baden-Württemberg",
    lat: 48.775, lng: 9.182, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Electrical Engineering", "Information Technology"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 190,
    admissionMode: "aptitude", testsRequired: { ielts: "6.5", gre: "recommended" }, needsVerification: true,
    description: "Microelectronics, communications, and embedded systems.",
  },
  {
    id: "stuttgart-cs", source: "curated", sourceUrl: "https://www.uni-stuttgart.de/en/study/", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "University of Stuttgart", institutionType: "uni", city: "Stuttgart", bundesland: "Baden-Württemberg",
    lat: 48.775, lng: 9.182, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 190,
    admissionMode: "aptitude", needsVerification: true, description: "English-taught CS master at Stuttgart.",
  },
  {
    id: "kit-optics", source: "curated", sourceUrl: "https://www.kit.edu/studying.php", retrievedAt: R,
    name: "Optics and Photonics", degree: "M.Sc.", courseType: "master",
    university: "Karlsruhe Institute of Technology", institutionType: "uni", city: "Karlsruhe", bundesland: "Baden-Württemberg",
    lat: 49.006, lng: 8.403, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Physics", "Photonics"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "aptitude", needsVerification: true, description: "Optical systems and photonic technologies at KIT.",
  },
  {
    id: "darmstadt-dss", source: "curated", sourceUrl: "https://www.tu-darmstadt.de/studieren/", retrievedAt: R,
    name: "Distributed Software Systems", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Darmstadt", institutionType: "uni", city: "Darmstadt", bundesland: "Hesse",
    lat: 49.872, lng: 8.651, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Distributed Systems"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 290,
    admissionMode: "nc", testsRequired: { ielts: "6.5" }, needsVerification: true,
    description: "Cloud, distributed, and software systems engineering.",
  },
  {
    id: "darmstadt-ice", source: "curated", sourceUrl: "https://www.tu-darmstadt.de/studieren/", retrievedAt: R,
    name: "Information and Communication Engineering", degree: "M.Sc.", courseType: "master",
    university: "Technical University of Darmstadt", institutionType: "uni", city: "Darmstadt", bundesland: "Hesse",
    lat: 49.872, lng: 8.651, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Electrical Engineering", "Communications"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 290,
    admissionMode: "nc", needsVerification: true, description: "Signal processing, communications, and embedded systems.",
  },
  {
    id: "mannheim-data-science", source: "curated", sourceUrl: "https://www.uni-mannheim.de/en/academics/", retrievedAt: R,
    name: "Data Science", degree: "M.Sc.", courseType: "master",
    university: "University of Mannheim", institutionType: "uni", city: "Mannheim", bundesland: "Baden-Württemberg",
    lat: 49.487, lng: 8.466, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Statistics"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 180,
    admissionMode: "aptitude", needsVerification: true, description: "Data science across CS, statistics, and economics.",
  },
  {
    id: "mannheim-management", source: "curated", sourceUrl: "https://www.uni-mannheim.de/en/academics/", retrievedAt: R,
    name: "Management", degree: "M.Sc.", courseType: "master",
    university: "University of Mannheim", institutionType: "uni", city: "Mannheim", bundesland: "Baden-Württemberg",
    lat: 49.487, lng: 8.466, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Management", "Business"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 180,
    admissionMode: "aptitude", testsRequired: { gmat: "recommended" }, needsVerification: true,
    description: "Top-ranked business school; selective management master.",
  },
  {
    id: "heidelberg-data-cs", source: "curated", sourceUrl: "https://www.uni-heidelberg.de/en/study", retrievedAt: R,
    name: "Data and Computer Science", degree: "M.Sc.", courseType: "master",
    university: "Heidelberg University", institutionType: "uni", city: "Heidelberg", bundesland: "Baden-Württemberg",
    lat: 49.398, lng: 8.672, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Data Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "aptitude", needsVerification: true, description: "Scientific computing, ML, and visual computing.",
  },
  {
    id: "heidelberg-physics", source: "curated", sourceUrl: "https://www.uni-heidelberg.de/en/study", retrievedAt: R,
    name: "Physics", degree: "M.Sc.", courseType: "master",
    university: "Heidelberg University", institutionType: "uni", city: "Heidelberg", bundesland: "Baden-Württemberg",
    lat: 49.398, lng: 8.672, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Physics"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "open", needsVerification: true, description: "Research-led physics master; English-taught.",
  },
  {
    id: "dresden-cms", source: "curated", sourceUrl: "https://tu-dresden.de/studium", retrievedAt: R,
    name: "Computational Modeling and Simulation", degree: "M.Sc.", courseType: "master",
    university: "TU Dresden", institutionType: "uni", city: "Dresden", bundesland: "Saxony",
    lat: 51.05, lng: 13.737, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Computational Engineering", "Simulation"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 280,
    admissionMode: "aptitude", needsVerification: true, description: "Modelling and simulation across engineering and science.",
  },
  {
    id: "dresden-dse", source: "curated", sourceUrl: "https://tu-dresden.de/studium", retrievedAt: R,
    name: "Distributed Systems Engineering", degree: "M.Sc.", courseType: "master",
    university: "TU Dresden", institutionType: "uni", city: "Dresden", bundesland: "Saxony",
    lat: 51.05, lng: 13.737, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science", "Distributed Systems"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 280,
    admissionMode: "nc", needsVerification: true, description: "Systems engineering for large-scale distributed software.",
  },
  {
    id: "freiburg-cs", source: "curated", sourceUrl: "https://www.uni-freiburg.de/en/studies", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "University of Freiburg", institutionType: "uni", city: "Freiburg", bundesland: "Baden-Württemberg",
    lat: 47.999, lng: 7.842, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: BW, semesterContribution: 160,
    admissionMode: "open", needsVerification: true, description: "Strong in ML, robotics, and bioinformatics.",
  },
  {
    id: "freiburg-reem", source: "curated", sourceUrl: "https://www.uni-freiburg.de/en/studies", retrievedAt: R,
    name: "Renewable Energy Engineering and Management", degree: "M.Sc.", courseType: "master",
    university: "University of Freiburg", institutionType: "uni", city: "Freiburg", bundesland: "Baden-Württemberg",
    lat: 47.999, lng: 7.842, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Engineering", areasOfStudy: ["Renewable Energy", "Engineering Management"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 160,
    admissionMode: "aptitude", needsVerification: true, description: "Energy technology with management and policy.",
  },
  {
    id: "tuebingen-ml", source: "curated", sourceUrl: "https://uni-tuebingen.de/en/study/", retrievedAt: R,
    name: "Machine Learning", degree: "M.Sc.", courseType: "master",
    university: "University of Tübingen", institutionType: "uni", city: "Tübingen", bundesland: "Baden-Württemberg",
    lat: 48.521, lng: 9.057, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Machine Learning", "Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: BW, semesterContribution: 170,
    admissionMode: "aptitude", needsVerification: true, description: "Dedicated ML master at a leading AI research hub.",
  },
  {
    id: "saarland-cs", source: "curated", sourceUrl: "https://www.uni-saarland.de/en/study.html", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "Saarland University", institutionType: "uni", city: "Saarbrücken", bundesland: "Saarland",
    lat: 49.235, lng: 6.996, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 300,
    admissionMode: "open", needsVerification: true, description: "Renowned CS faculty (MPI, CISPA, DFKI on campus).",
  },
  {
    id: "saarland-dsai", source: "curated", sourceUrl: "https://www.uni-saarland.de/en/study.html", retrievedAt: R,
    name: "Data Science and Artificial Intelligence", degree: "M.Sc.", courseType: "master",
    university: "Saarland University", institutionType: "uni", city: "Saarbrücken", bundesland: "Saarland",
    lat: 49.235, lng: 6.996, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Artificial Intelligence"],
    mode: "full_time", semesters: 4, intake: "both", tuitionPerSemester: null, semesterContribution: 300,
    admissionMode: "open", needsVerification: true, description: "AI and data science with strong research ties.",
  },
  {
    id: "bonn-cs", source: "curated", sourceUrl: "https://www.uni-bonn.de/en/studying", retrievedAt: R,
    name: "Computer Science", degree: "M.Sc.", courseType: "master",
    university: "University of Bonn", institutionType: "uni", city: "Bonn", bundesland: "North Rhine-Westphalia",
    lat: 50.737, lng: 7.098, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", needsVerification: true, description: "Research-focused CS; intelligent systems and graphics.",
  },
  {
    id: "lmu-data-science", source: "curated", sourceUrl: "https://www.lmu.de/en/study/index.html", retrievedAt: R,
    name: "Data Science", degree: "M.Sc.", courseType: "master",
    university: "LMU Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "en", languageLevelEn: "IELTS 6.5",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science", "Statistics"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "aptitude", needsVerification: true, description: "Statistics-rooted data science master at LMU.",
  },
  {
    id: "goettingen-ads", source: "curated", sourceUrl: "https://www.uni-goettingen.de/en/", retrievedAt: R,
    name: "Applied Data Science", degree: "M.Sc.", courseType: "master",
    university: "University of Göttingen", institutionType: "uni", city: "Göttingen", bundesland: "Lower Saxony",
    lat: 51.541, lng: 9.915, languages: "en", languageLevelEn: "IELTS 6.0",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Data Science"],
    mode: "full_time", semesters: 4, intake: "winter", tuitionPerSemester: null, semesterContribution: 380,
    admissionMode: "open", needsVerification: true, description: "Applied, interdisciplinary data science.",
  },

  // ── Bachelor's (post-Class-12; usually via Studienkolleg/HZB — addendum §4) ──────────────────────
  {
    id: "freiburg-las-ba", source: "curated", sourceUrl: "https://www.ucf.uni-freiburg.de/", retrievedAt: R,
    name: "Liberal Arts and Sciences", degree: "B.A.", courseType: "bachelor",
    university: "University of Freiburg", institutionType: "uni", city: "Freiburg", bundesland: "Baden-Württemberg",
    lat: 47.999, lng: 7.842, languages: "en", languageLevelEn: "IELTS 6.5 / TOEFL 87",
    subjectGroup: "Language & Cultural Studies", areasOfStudy: ["Liberal Arts", "Interdisciplinary"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: BW, semesterContribution: 175,
    admissionMode: "aptitude", needsVerification: true,
    description: "English-taught interdisciplinary B.A. at University College Freiburg (public).",
  },
  {
    id: "tum-informatik-bsc", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs", retrievedAt: R,
    name: "Informatik (Computer Science)", degree: "B.Sc.", courseType: "bachelor",
    university: "Technical University of Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "aptitude", needsVerification: true,
    description: "German-taught CS bachelor; school-leavers usually need a Studienkolleg/HZB first.",
  },
  {
    id: "rwth-maschinenbau-bsc", source: "curated", sourceUrl: "https://www.rwth-aachen.de/cms/root/studium/Vor-dem-Studium/lidx/1/", retrievedAt: R,
    name: "Maschinenbau (Mechanical Engineering)", degree: "B.Sc.", courseType: "bachelor",
    university: "RWTH Aachen University", institutionType: "uni", city: "Aachen", bundesland: "North Rhine-Westphalia",
    lat: 50.776, lng: 6.083, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Engineering", areasOfStudy: ["Mechanical Engineering"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", needsVerification: true,
    description: "German-taught mechanical engineering bachelor (NC). Studienkolleg/HZB usually required first.",
  },
  {
    id: "mannheim-bwl-bsc", source: "curated", sourceUrl: "https://www.uni-mannheim.de/en/academics/before-your-studies/", retrievedAt: R,
    name: "Betriebswirtschaftslehre (Business Administration)", degree: "B.Sc.", courseType: "bachelor",
    university: "University of Mannheim", institutionType: "uni", city: "Mannheim", bundesland: "Baden-Württemberg",
    lat: 49.487, lng: 8.466, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Business Administration"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: BW, semesterContribution: 180,
    admissionMode: "nc", needsVerification: true,
    description: "Germany's top-ranked BWL bachelor (NC); German-taught.",
  },
  {
    id: "heidelberg-physik-bsc", source: "curated", sourceUrl: "https://www.uni-heidelberg.de/en/study", retrievedAt: R,
    name: "Physik (Physics)", degree: "B.Sc.", courseType: "bachelor",
    university: "Heidelberg University", institutionType: "uni", city: "Heidelberg", bundesland: "Baden-Württemberg",
    lat: 49.41, lng: 8.71, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Physics"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: BW, semesterContribution: 180,
    admissionMode: "open", needsVerification: true,
    description: "German-taught physics bachelor at a leading research university.",
  },
  {
    id: "tuberlin-informatik-bsc", source: "curated", sourceUrl: "https://www.tu.berlin/en/studying", retrievedAt: R,
    name: "Informatik (Computer Science)", degree: "B.Sc.", courseType: "bachelor",
    university: "Technische Universität Berlin", institutionType: "uni", city: "Berlin", bundesland: "Berlin",
    lat: 52.512, lng: 13.327, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Computer Science"],
    mode: "full_time", semesters: 6, intake: "both", tuitionPerSemester: null, semesterContribution: 310,
    admissionMode: "open", needsVerification: true,
    description: "German-taught CS bachelor in Berlin (no tuition; Semesterbeitrag only).",
  },

  // ── Medicine (Humanmedizin) — integrated Staatsexamen, German-taught, NC (addendum §3) ───────────
  {
    id: "charite-medizin", source: "curated", sourceUrl: "https://www.charite.de/en/studies/", retrievedAt: R,
    name: "Humanmedizin (Medicine)", degree: "Staatsexamen", courseType: "medicine",
    university: "Charité – Universitätsmedizin Berlin", institutionType: "uni", city: "Berlin", bundesland: "Berlin",
    lat: 52.526, lng: 13.376, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Medicine & Health", areasOfStudy: ["Medicine"],
    mode: "full_time", semesters: 13, intake: "winter", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", needsVerification: true,
    description: "German-taught integrated medicine → Staatsexamen (NC; non-EU via per-university quota). No English-taught public medicine.",
  },
  {
    id: "heidelberg-medizin", source: "curated", sourceUrl: "https://www.medizinische-fakultaet-hd.uni-heidelberg.de/", retrievedAt: R,
    name: "Humanmedizin (Medicine)", degree: "Staatsexamen", courseType: "medicine",
    university: "Heidelberg University", institutionType: "uni", city: "Heidelberg", bundesland: "Baden-Württemberg",
    lat: 49.41, lng: 8.71, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Medicine & Health", areasOfStudy: ["Medicine"],
    mode: "full_time", semesters: 13, intake: "winter", tuitionPerSemester: BW, semesterContribution: 180,
    admissionMode: "nc", needsVerification: true,
    description: `Top-ranked German-taught medicine (NC). Baden-Württemberg charges €${TUITION_BW_EUR.toLocaleString("en-US")}/sem for non-EU students.`,
  },
  {
    id: "lmu-medizin", source: "curated", sourceUrl: "https://www.lmu.de/en/study/", retrievedAt: R,
    name: "Humanmedizin (Medicine)", degree: "Staatsexamen", courseType: "medicine",
    university: "LMU Munich", institutionType: "uni", city: "Munich", bundesland: "Bavaria",
    lat: 48.137, lng: 11.575, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Medicine & Health", areasOfStudy: ["Medicine"],
    mode: "full_time", semesters: 13, intake: "winter", tuitionPerSemester: null, semesterContribution: 150,
    admissionMode: "nc", needsVerification: true,
    description: "German-taught integrated medicine at LMU (highly NC-restricted).",
  },
  {
    id: "hamburg-medizin", source: "curated", sourceUrl: "https://www.uni-hamburg.de/en/", retrievedAt: R,
    name: "Humanmedizin (Medicine)", degree: "Staatsexamen", courseType: "medicine",
    university: "University of Hamburg", institutionType: "uni", city: "Hamburg", bundesland: "Hamburg",
    lat: 53.567, lng: 9.985, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Medicine & Health", areasOfStudy: ["Medicine"],
    mode: "full_time", semesters: 13, intake: "winter", tuitionPerSemester: null, semesterContribution: 335,
    admissionMode: "nc", needsVerification: true,
    description: "German-taught medicine (iMED model curriculum); NC.",
  },
  {
    id: "rwth-medizin", source: "curated", sourceUrl: "https://www.rwth-aachen.de/cms/root/studium/Vor-dem-Studium/lidx/1/", retrievedAt: R,
    name: "Humanmedizin (Medicine)", degree: "Staatsexamen", courseType: "medicine",
    university: "RWTH Aachen University", institutionType: "uni", city: "Aachen", bundesland: "North Rhine-Westphalia",
    lat: 50.776, lng: 6.083, languages: "de", languageLevelDe: "C1 (DSH-2 / TestDaF TDN 4)",
    subjectGroup: "Medicine & Health", areasOfStudy: ["Medicine"],
    mode: "full_time", semesters: 13, intake: "winter", tuitionPerSemester: null, semesterContribution: 320,
    admissionMode: "nc", needsVerification: true,
    description: "German-taught model-curriculum medicine at RWTH; NC.",
  },

  // ── Bachelor's — grounded expansion (research 2026-06-21; real official pages, all needsVerification) ──
  {
    id: "fu-berlin-north-american-studies-ba", source: "curated", sourceUrl: "https://www.jfki.fu-berlin.de/en/academics/ba/index.html", retrievedAt: "2026-06-21",
    name: "North American Studies", degree: "B.A.", courseType: "bachelor",
    university: "Freie Universität Berlin", institutionType: "uni", city: "Berlin", bundesland: "Berlin",
    lat: 52.447, lng: 13.288, languages: "en", languageLevelEn: "English C1",
    subjectGroup: "Language & Cultural Studies", areasOfStudy: ["North American Studies", "Area Studies"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, admissionMode: "nc", needsVerification: true,
    description: "English-taught area-studies B.A. at the JFK Institute (mandatory semester abroad); confirm admission + fees.",
  },
  {
    id: "rhine-waal-international-relations-ba", source: "curated", sourceUrl: "https://www.hochschule-rhein-waal.de/en/faculties/society-and-economics/degree-programmes/international-relations-ba", retrievedAt: "2026-06-21",
    name: "International Relations", degree: "B.A.", courseType: "bachelor",
    university: "Rhine-Waal University of Applied Sciences", institutionType: "uas", city: "Kleve", bundesland: "North Rhine-Westphalia",
    lat: 51.788, lng: 6.138, languages: "en", languageLevelEn: "IELTS / TOEFL ≥ B2",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["International Politics", "International Economics", "International Law"],
    mode: "full_time", semesters: 7, intake: "winter", tuitionPerSemester: null, semesterContribution: 300, admissionMode: "nc", needsVerification: true,
    description: "English-taught IR at a public university of applied sciences; restricted + an 8-week preparatory internship.",
  },
  {
    id: "muenster-information-systems-bsc", source: "curated", sourceUrl: "https://www.wi.uni-muenster.de/applicationadmission-bachelor-science-information-systems", retrievedAt: "2026-06-21",
    name: "Information Systems", degree: "B.Sc.", courseType: "bachelor",
    university: "University of Münster", institutionType: "uni", city: "Münster", bundesland: "North Rhine-Westphalia",
    lat: 51.961, lng: 7.628, languages: "en",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Information Systems", "Business Informatics"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, admissionMode: "nc", needsVerification: true,
    description: "English-taught Information Systems (Wirtschaftsinformatik); good German recommended — confirm cert level.",
  },
  {
    id: "bayreuth-philosophy-economics-ba", source: "curated", sourceUrl: "https://www.uni-bayreuth.de/en/bachelor/philosophy-and-economics", retrievedAt: "2026-06-21",
    name: "Philosophy & Economics", degree: "B.A.", courseType: "bachelor",
    university: "University of Bayreuth", institutionType: "uni", city: "Bayreuth", bundesland: "Bavaria",
    lat: 49.928, lng: 11.586, languages: "de_en", languageLevelDe: "German B2 (essential)",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Philosophy", "Economics", "PPE"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, admissionMode: "nc", needsVerification: true,
    description: "Partly German-taught PPE-style B.A. Bavaria levies non-EU tuition — confirm the amount on the official page.",
  },
  {
    id: "tu-berlin-computer-engineering-bsc", source: "curated", sourceUrl: "https://www.tu.berlin/en/studying/study-programs/all-programs-offered/study-course/computer-engineering-b-sc", retrievedAt: "2026-06-21",
    name: "Computer Engineering", degree: "B.Sc.", courseType: "bachelor",
    university: "Technische Universität Berlin", institutionType: "uni", city: "Berlin", bundesland: "Berlin",
    lat: 52.512, lng: 13.327, languages: "de", languageLevelDe: "German required (verify level)",
    subjectGroup: "Engineering", areasOfStudy: ["Computer Engineering"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, admissionMode: "nc", needsVerification: true,
    description: "German-taught computer engineering at TU Berlin; no tuition (Semesterbeitrag only).",
  },
  {
    id: "tum-mechanical-engineering-bsc", source: "curated", sourceUrl: "https://www.tum.de/en/studies/degree-programs/detail/mechanical-engineering-bachelor-of-science-bsc", retrievedAt: "2026-06-21",
    name: "Mechanical Engineering (Maschinenwesen)", degree: "B.Sc.", courseType: "bachelor",
    university: "Technical University of Munich", institutionType: "uni", city: "Garching (Munich)", bundesland: "Bavaria",
    lat: 48.249, lng: 11.651, languages: "de", languageLevelDe: "German required (verify level)",
    subjectGroup: "Engineering", areasOfStudy: ["Mechanical Engineering"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: 3000, admissionMode: "aptitude", needsVerification: true,
    description: "German-taught; TUM aptitude assessment + 8-week internship. Bavaria non-EU tuition €3,000/sem (confirmed on the TUM page).",
  },
  {
    id: "stuttgart-mechanical-engineering-bsc", source: "curated", sourceUrl: "https://www.uni-stuttgart.de/en/study/bachelor-programs/mechanical-engineering-b.sc./", retrievedAt: "2026-06-21",
    name: "Mechanical Engineering (Maschinenbau)", degree: "B.Sc.", courseType: "bachelor",
    university: "University of Stuttgart", institutionType: "uni", city: "Stuttgart", bundesland: "Baden-Württemberg",
    lat: 48.745, lng: 9.107, languages: "de", languageLevelDe: "German required (verify level)",
    subjectGroup: "Engineering", areasOfStudy: ["Mechanical Engineering"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: BW, admissionMode: "open", needsVerification: true,
    description: "German-taught; admission unrestricted + a pre-study internship. BW non-EU tuition applies.",
  },
  {
    id: "bonn-economics-bsc", source: "curated", sourceUrl: "https://www.uni-bonn.de/en/studying/degree-programs/degree-programs-a-z/economics-bsc", retrievedAt: "2026-06-21",
    name: "Economics (Volkswirtschaftslehre)", degree: "B.Sc.", courseType: "bachelor",
    university: "University of Bonn", institutionType: "uni", city: "Bonn", bundesland: "North Rhine-Westphalia",
    lat: 50.737, lng: 7.098, languages: "de", languageLevelDe: "German DSH-1 (B2)",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Economics", "Quantitative Methods"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, admissionMode: "open", needsVerification: true,
    description: "German-taught economics; open admission, DSH-1/B2. No tuition (NRW).",
  },
  {
    id: "kiel-economics-bsc", source: "curated", sourceUrl: "https://www.uni-kiel.de/en/wiso/studying/bachelor/economics", retrievedAt: "2026-06-21",
    name: "Economics (Volkswirtschaftslehre)", degree: "B.Sc.", courseType: "bachelor",
    university: "Kiel University", institutionType: "uni", city: "Kiel", bundesland: "Schleswig-Holstein",
    lat: 54.339, lng: 10.122, languages: "de",
    subjectGroup: "Law, Economics & Social Sciences", areasOfStudy: ["Economics", "Econometrics"],
    mode: "full_time", semesters: 6, intake: "both", tuitionPerSemester: null, admissionMode: "open", needsVerification: true,
    description: "Economics B.Sc.; admission-free, winter or summer start. Instruction language — verify.",
  },
  {
    id: "heidelberg-molecular-biotechnology-bsc", source: "curated", sourceUrl: "https://www.uni-heidelberg.de/en/study/all-subjects/molecular-biotechnology/molecular-biotechnology-bachelor-100", retrievedAt: "2026-06-21",
    name: "Molecular Biotechnology", degree: "B.Sc.", courseType: "bachelor",
    university: "Heidelberg University", institutionType: "uni", city: "Heidelberg", bundesland: "Baden-Württemberg",
    lat: 49.41, lng: 8.71, languages: "de", languageLevelDe: "Very good German (verify level)",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Molecular Biotechnology", "Biochemistry"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: BW, admissionMode: "nc", needsVerification: true,
    description: "German-taught molecular biotechnology; NC via the dialogue-oriented procedure (DoSV). BW non-EU tuition applies.",
  },
  {
    id: "tu-dresden-molecular-biology-biotechnology-bsc", source: "curated", sourceUrl: "https://tu-dresden.de/studium/vor-dem-studium/studienangebot/sins/sins_studiengang?autoid=313&set_language=en", retrievedAt: "2026-06-21",
    name: "Molecular Biology and Biotechnology", degree: "B.Sc.", courseType: "bachelor",
    university: "Technische Universität Dresden", institutionType: "uni", city: "Dresden", bundesland: "Saxony",
    lat: 51.028, lng: 13.726, languages: "de",
    subjectGroup: "Mathematics & Natural Sciences", areasOfStudy: ["Molecular Biology", "Biotechnology"],
    mode: "full_time", semesters: 6, intake: "winter", tuitionPerSemester: null, admissionMode: "nc", needsVerification: true,
    description: "German-taught molecular biology & biotechnology B.Sc. (TU Dresden); confirm details on the official page.",
  },
];
