/* AUTO-GENERATED by scripts/gen-pages.mjs — do not edit by hand.
 * Single source of truth for the route table: path, page metadata, lazy component, and nav grouping.
 * Re-run `node scripts/gen-pages.mjs` to regenerate after editing the PAGES list in that script. */
import { lazy, type ComponentType, type LazyExoticComponent } from "react";
import {
  Accessibility,
  Activity,
  Award,
  Backpack,
  BarChart3,
  BellRing,
  BookOpen,
  BookOpenCheck,
  Briefcase,
  Building2,
  Calculator,
  CalendarDays,
  CalendarRange,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Coins,
  Columns3,
  Eye,
  FileBadge,
  FileCheck,
  FileSearch,
  FileText,
  FolderCheck,
  FolderLock,
  Gauge,
  Globe,
  GraduationCap,
  Headphones,
  HeartPulse,
  Info,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Library,
  ListChecks,
  Map,
  MapPin,
  MessageSquare,
  Mic,
  PenLine,
  Plane,
  ScanLine,
  School,
  ScrollText,
  Settings,
  ShieldCheck,
  Sigma,
  Sparkles,
  Stamp,
  Target,
  TramFront,
  TrendingUp,
  UserCircle,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import type { FeatureCategoryKey } from "@/lib/types";

export type NavGroupKey =
  | "overview"
  | "profile"
  | "documents"
  | "language"
  | "finance"
  | "visa"
  | "campus"
  | "system";

export const NAV_GROUPS: Record<NavGroupKey, string> = {
  overview: "Overview",
  profile: "Profile & Assessment",
  documents: "Document Prep",
  language: "Language & Test Prep",
  finance: "Finance & Logistics",
  visa: "Visa & Relocation",
  campus: "Campus Life",
  system: "System",
};

export interface NavItem {
  path: string;
  label: string;
  title: string;
  eyebrow?: string;
  description?: string;
  group: NavGroupKey;
  category?: FeatureCategoryKey;
  icon: LucideIcon;
  /** 1–30 for the canonical features (feature-matrix.md). */
  featureNo?: number;
  /** Hidden from the sidebar (sub-pages, 404). */
  hide?: boolean;
  /** Requires the finance/visa advisory disclaimer. */
  disclaimer?: boolean;
  Component: LazyExoticComponent<ComponentType>;
}

const Dashboard = lazy(() => import("@/pages/overview/Dashboard"));
const RoadmapPage = lazy(() => import("@/pages/overview/Roadmap"));
const ProcessPage = lazy(() => import("@/pages/overview/Process"));
const DeadlinesPage = lazy(() => import("@/pages/overview/Deadlines"));
const EventsPage = lazy(() => import("@/pages/overview/Events"));
const DocumentsHubPage = lazy(() => import("@/pages/overview/DocumentsHub"));
const TimelinePage = lazy(() => import("@/pages/overview/Timeline"));
const SourcesPage = lazy(() => import("@/pages/overview/Sources"));
const TrackerPage = lazy(() => import("@/pages/overview/Tracker"));
const CalendarPage = lazy(() => import("@/pages/overview/Calendar"));
const ProfileOverview = lazy(() => import("@/pages/profile/Overview"));
const ProfileParse = lazy(() => import("@/pages/profile/Parse"));
const ProfileEvaluate = lazy(() => import("@/pages/profile/Evaluate"));
const ProfileMatching = lazy(() => import("@/pages/profile/Matching"));
const ProfileSkillGap = lazy(() => import("@/pages/profile/SkillGap"));
const ProfileEcts = lazy(() => import("@/pages/profile/Ects"));
const UniversitiesExplorer = lazy(() => import("@/pages/profile/Universities"));
const DocumentsOverview = lazy(() => import("@/pages/documents/Overview"));
const DocumentsSop = lazy(() => import("@/pages/documents/Sop"));
const DocumentsCv = lazy(() => import("@/pages/documents/Cv"));
const DocumentsLor = lazy(() => import("@/pages/documents/Lor"));
const DocumentsUniAssist = lazy(() => import("@/pages/documents/UniAssist"));
const DocumentsVpd = lazy(() => import("@/pages/documents/Vpd"));
const DocumentsTranslation = lazy(() => import("@/pages/documents/Translation"));
const DocumentsVault = lazy(() => import("@/pages/documents/Vault"));
const LanguageOverview = lazy(() => import("@/pages/language/Overview"));
const LanguageGerman = lazy(() => import("@/pages/language/German"));
const LanguageFlashcards = lazy(() => import("@/pages/language/Flashcards"));
const LanguageIeltsToefl = lazy(() => import("@/pages/language/IeltsToefl"));
const LanguageGreGmat = lazy(() => import("@/pages/language/GreGmat"));
const LanguageGoetheTestdaf = lazy(() => import("@/pages/language/GoetheTestdaf"));
const LanguageExamsHub = lazy(() => import("@/pages/language/ExamsHub"));
const ExamIelts = lazy(() => import("@/pages/language/exams/Ielts"));
const ExamToefl = lazy(() => import("@/pages/language/exams/Toefl"));
const ExamTestdaf = lazy(() => import("@/pages/language/exams/Testdaf"));
const ExamGoethe = lazy(() => import("@/pages/language/exams/Goethe"));
const ExamGre = lazy(() => import("@/pages/language/exams/Gre"));
const ExamGmat = lazy(() => import("@/pages/language/exams/Gmat"));
const FinanceOverview = lazy(() => import("@/pages/finance/Overview"));
const FinanceSperrkonto = lazy(() => import("@/pages/finance/Sperrkonto"));
const FinanceCostOfLiving = lazy(() => import("@/pages/finance/CostOfLiving"));
const FinanceHealthInsurance = lazy(() => import("@/pages/finance/HealthInsurance"));
const FinanceScholarships = lazy(() => import("@/pages/finance/Scholarships"));
const FinanceWork = lazy(() => import("@/pages/finance/Work"));
const VisaOverview = lazy(() => import("@/pages/visa/Overview"));
const VisaSimulator = lazy(() => import("@/pages/visa/Simulator"));
const VisaChecklist = lazy(() => import("@/pages/visa/Checklist"));
const VisaAps = lazy(() => import("@/pages/visa/Aps"));
const VisaAccommodation = lazy(() => import("@/pages/visa/Accommodation"));
const VisaAnmeldung = lazy(() => import("@/pages/visa/Anmeldung"));
const CampusOverview = lazy(() => import("@/pages/campus/Overview"));
const CampusPreDeparture = lazy(() => import("@/pages/campus/PreDeparture"));
const CampusNetworking = lazy(() => import("@/pages/campus/Networking"));
const CampusDeutschlandticket = lazy(() => import("@/pages/campus/Deutschlandticket"));
const CampusCulture = lazy(() => import("@/pages/campus/Culture"));
const AboutPage = lazy(() => import("@/pages/system/About"));
const SettingsPage = lazy(() => import("@/pages/system/Settings"));
const HelpPage = lazy(() => import("@/pages/system/Help"));
const PrivacyPage = lazy(() => import("@/pages/system/Privacy"));
const TermsPage = lazy(() => import("@/pages/system/Terms"));
const AccessibilityPage = lazy(() => import("@/pages/system/Accessibility"));
const NotFoundPage = lazy(() => import("@/pages/system/NotFound"));

export const NAV: NavItem[] = [
  { path: "/", label: "Dashboard", title: "Application dashboard", eyebrow: "Übersicht · Overview", description: "Your German Master's application at a glance — profile, roadmap, deadlines, and progress across all six areas.", group: "overview", icon: LayoutDashboard, Component: Dashboard },
  { path: "/roadmap", label: "Roadmap", title: "Step-by-step roadmap", eyebrow: "Aktenplan · Roadmap", description: "A dependency-ordered plan from profile evaluation to enrolment. Each step links to the tool that completes it.", group: "overview", icon: Map, Component: RoadmapPage },
  { path: "/process", label: "Application status", title: "Application status board", eyebrow: "Bearbeitungsstand · Status", description: "Process polling for every application thread — where each one stands in the not-started → submitted → complete pipeline.", group: "overview", icon: Activity, Component: ProcessPage },
  { path: "/deadlines", label: "Deadlines & alerts", title: "Deadlines & alerts", eyebrow: "Fristen · Deadlines", description: "Every date that matters, soonest first, with urgency computed deterministically. Official dates that change yearly are flagged for verification.", group: "overview", icon: BellRing, Component: DeadlinesPage },
  { path: "/events", label: "Event watch", title: "Event watch", eyebrow: "Terminüberwachung · Event watch", description: "Recurring windows worth watching — portal openings, intake cycles, scholarship rounds, and visa-appointment lead times.", group: "overview", icon: Eye, Component: EventsPage },
  { path: "/documents-checklist", label: "Document gathering", title: "Document gathering", eyebrow: "Unterlagen · Documents", description: "Master checklists for the whole journey: application, APS, visa, and enrolment paperwork — with where to obtain each.", group: "overview", icon: FolderCheck, Component: DocumentsHubPage },
  { path: "/timeline", label: "Timeline", title: "Preparation timeline", eyebrow: "Zeitplan · Timeline", description: "A month-by-month view of the typical 12–18 month preparation arc, from first research to arrival in Germany.", group: "overview", icon: CalendarRange, Component: TimelinePage },
  { path: "/sources", label: "Sources", title: "Source registry", eyebrow: "Quellen · Sources", description: "Every official source DeutschPrep cites. Specific figures are grounded against these or flagged for verification.", group: "overview", icon: Library, Component: SourcesPage },
  { path: "/tracker", label: "Application tracker", title: "Application tracker", eyebrow: "Bewerbungen · Tracker", description: "A Kanban board of every programme you're applying to — from researching to decision. Syncs to your account.", group: "overview", icon: Columns3, Component: TrackerPage },
  { path: "/calendar", label: "Deadline calendar", title: "Deadline calendar", eyebrow: "Kalender · Calendar", description: "Every application, VPD, visa, and Sperrkonto date on a month grid — plus deadlines you add yourself.", group: "overview", icon: CalendarDays, Component: CalendarPage },
  { path: "/profile", label: "Overview", title: "Profile & Assessment", eyebrow: "Bereich A · Profile & Assessment", description: "Turn your resume into a German-readable academic profile: parsed facts, a converted grade, matched programs, and skill gaps.", group: "profile", category: "profile", icon: UserCircle, Component: ProfileOverview },
  { path: "/profile/parse", label: "Resume / LinkedIn parsing", title: "Resume & LinkedIn parsing", eyebrow: "Feature 01 · Profile", description: "Extract structured facts from a resume, LinkedIn export, or intake form — handled as personal data.", group: "profile", category: "profile", icon: ScanLine, featureNo: 1, Component: ProfileParse },
  { path: "/profile/evaluate", label: "Profile evaluation (GPA)", title: "Profile evaluation — GPA → German grade", eyebrow: "Feature 02 · Profile", description: "Convert your grade to the German 1.0–4.0 scale with the deterministic Modified Bavarian Formula.", group: "profile", category: "profile", icon: Gauge, featureNo: 2, Component: ProfileEvaluate },
  { path: "/profile/matching", label: "University matching", title: "Course & university matching", eyebrow: "Feature 03 · Profile", description: "Shortlist Master's programs at German public universities that fit your background and goals.", group: "profile", category: "profile", icon: GraduationCap, featureNo: 3, Component: ProfileMatching },
  { path: "/profile/skill-gap", label: "Skill-gap analysis", title: "Skill-gap analysis", eyebrow: "Feature 04 · Profile", description: "See what target programs expect that your profile doesn't yet show — and how to close each gap.", group: "profile", category: "profile", icon: Target, featureNo: 4, Component: ProfileSkillGap },
  { path: "/profile/ects", label: "ECTS calculator", title: "ECTS calculator", eyebrow: "Feature 05 · Profile", description: "Total and normalize your credits to ECTS so admissions can compare your degree to a German one.", group: "profile", category: "profile", icon: Calculator, featureNo: 5, Component: ProfileEcts },
  { path: "/universities", label: "Universities explorer", title: "Universities & programs explorer", eyebrow: "Hochschulen · Universities", description: "Browse and compare Master's programmes at German public universities, with grounded requirements you can re-verify.", group: "profile", category: "profile", icon: School, Component: UniversitiesExplorer },
  { path: "/documents", label: "Overview", title: "Document Prep", eyebrow: "Bereich B · Document Prep", description: "Draft and track every document an application needs: SOP, CV, recommendation letters, and the uni-assist workflow.", group: "documents", category: "documents", icon: FileText, Component: DocumentsOverview },
  { path: "/documents/sop", label: "Statement of Purpose", title: "Statement of Purpose generator", eyebrow: "Feature 06 · Documents", description: "Build a tailored SOP from your profile and a target program — structured, specific, and yours to edit.", group: "documents", category: "documents", icon: PenLine, featureNo: 6, Component: DocumentsSop },
  { path: "/documents/cv", label: "Europass CV", title: "Europass CV builder", eyebrow: "Feature 07 · Documents", description: "Produce a Europass-format CV, the European standard German universities recognize.", group: "documents", category: "documents", icon: FileBadge, featureNo: 7, Component: DocumentsCv },
  { path: "/documents/lor", label: "Recommendation letters", title: "Letter of Recommendation templates", eyebrow: "Feature 08 · Documents", description: "Give recommenders a strong starting draft tailored to the program and your relationship.", group: "documents", category: "documents", icon: ScrollText, featureNo: 8, Component: DocumentsLor },
  { path: "/documents/uni-assist", label: "Uni-Assist walkthrough", title: "Uni-Assist walkthrough", eyebrow: "Feature 09 · Documents", description: "Step through the uni-assist application: account, programs, documents, fees, and what happens after you submit.", group: "documents", category: "documents", icon: ClipboardList, featureNo: 9, Component: DocumentsUniAssist },
  { path: "/documents/vpd", label: "VPD tracker", title: "VPD (Preliminary Documentation) tracker", eyebrow: "Feature 10 · Documents", description: "Track the Vorprüfungsdokumentation some universities require before you apply directly.", group: "documents", category: "documents", icon: FileCheck, featureNo: 10, Component: DocumentsVpd },
  { path: "/documents/translation", label: "Translation assistant", title: "Translation assistant", eyebrow: "Feature 11 · Documents", description: "Understand which documents need certified translations and prepare drafts to hand to a sworn translator.", group: "documents", category: "documents", icon: Languages, featureNo: 11, Component: DocumentsTranslation },
  { path: "/vault", label: "Document vault", title: "Document vault", eyebrow: "Tresor · Vault", description: "One place for your SOP, CV, recommendation letters, transcripts, and certificates — synced to your account.", group: "documents", category: "documents", icon: FolderLock, Component: DocumentsVault },
  { path: "/language", label: "Overview", title: "Language & Test Prep", eyebrow: "Bereich C · Language & Test", description: "Reach the German or English level your program requires, and rehearse every admission test with timed mocks.", group: "language", category: "language", icon: Languages, Component: LanguageOverview },
  { path: "/language/german", label: "German A1–B2 (+TTS)", title: "German A1–B2 course", eyebrow: "Feature 12 · Language", description: "A structured path from beginner to B2, with audio practice for listening and pronunciation.", group: "language", category: "language", icon: BookOpen, featureNo: 12, Component: LanguageGerman },
  { path: "/language/flashcards", label: "SRS flashcards", title: "Spaced-repetition flashcards", eyebrow: "Feature 13 · Language", description: "Memorize vocabulary efficiently with a spaced-repetition schedule that surfaces cards right before you'd forget them.", group: "language", category: "language", icon: Layers, featureNo: 13, Component: LanguageFlashcards },
  { path: "/language/ielts-toefl", label: "IELTS / TOEFL prep", title: "IELTS & TOEFL preparation", eyebrow: "Feature 14 · Language", description: "Understand the formats, target the right band/score, and practice with timed section mocks.", group: "language", category: "language", icon: Headphones, featureNo: 14, Component: LanguageIeltsToefl },
  { path: "/language/gre-gmat", label: "GRE / GMAT checker", title: "GRE / GMAT requirement checker", eyebrow: "Feature 15 · Language", description: "Find out whether your target programs require GRE or GMAT, and what scores are competitive.", group: "language", category: "language", icon: BarChart3, featureNo: 15, Component: LanguageGreGmat },
  { path: "/language/goethe-testdaf", label: "Goethe / TestDaF guides", title: "Goethe & TestDaF guides", eyebrow: "Feature 16 · Language", description: "Pick the right German certificate (TestDaF, DSH, Goethe, telc) and prepare for each section.", group: "language", category: "language", icon: BookOpenCheck, featureNo: 16, Component: LanguageGoetheTestdaf },
  { path: "/language/exams", label: "Mock exams", title: "Mock exam centre", eyebrow: "Übungstests · Mock exams", description: "Timed practice exams for every test you might need: IELTS, TOEFL, TestDaF, Goethe, GRE, and GMAT.", group: "language", category: "language", icon: ClipboardCheck, Component: LanguageExamsHub },
  { path: "/language/exams/ielts", label: "IELTS mock", title: "IELTS Academic — practice exam", eyebrow: "Übungstest · IELTS", description: "A timed IELTS Academic practice set across Listening, Reading, and Writing question types.", group: "language", category: "language", icon: Headphones, hide: true, Component: ExamIelts },
  { path: "/language/exams/toefl", label: "TOEFL mock", title: "TOEFL iBT — practice exam", eyebrow: "Übungstest · TOEFL", description: "A timed TOEFL iBT practice set across Reading and Listening question types.", group: "language", category: "language", icon: Globe, hide: true, Component: ExamToefl },
  { path: "/language/exams/testdaf", label: "TestDaF mock", title: "TestDaF — practice exam", eyebrow: "Übungstest · TestDaF", description: "A timed TestDaF practice set mapped to the TDN 3–5 band scale.", group: "language", category: "language", icon: Languages, hide: true, Component: ExamTestdaf },
  { path: "/language/exams/goethe", label: "Goethe mock", title: "Goethe-Zertifikat — practice exam", eyebrow: "Übungstest · Goethe", description: "A timed CEFR-aligned German practice set (A2–B2 grammar, vocabulary, and reading).", group: "language", category: "language", icon: MessageSquare, hide: true, Component: ExamGoethe },
  { path: "/language/exams/gre", label: "GRE mock", title: "GRE General — practice exam", eyebrow: "Übungstest · GRE", description: "A timed GRE practice set across Verbal Reasoning and Quantitative Reasoning question types.", group: "language", category: "language", icon: Sigma, hide: true, Component: ExamGre },
  { path: "/language/exams/gmat", label: "GMAT mock", title: "GMAT Focus — practice exam", eyebrow: "Übungstest · GMAT", description: "A timed GMAT Focus practice set across Quantitative, Verbal, and Data Insights question types.", group: "language", category: "language", icon: TrendingUp, hide: true, Component: ExamGmat },
  { path: "/finance", label: "Overview", title: "Finance & Logistics", eyebrow: "Bereich D · Finance & Logistics", description: "Plan the money side: blocked account, monthly costs, health insurance, scholarships, and part-time work.", group: "finance", category: "finance", icon: Wallet, disclaimer: true, Component: FinanceOverview },
  { path: "/finance/sperrkonto", label: "Sperrkonto guide", title: "Blocked account (Sperrkonto) guide", eyebrow: "Feature 17 · Finance", description: "Understand the blocked account you need for the visa: how it works, the required amount, and which providers to use.", group: "finance", category: "finance", icon: Landmark, featureNo: 17, disclaimer: true, Component: FinanceSperrkonto },
  { path: "/finance/cost-of-living", label: "Cost-of-living calc", title: "Cost-of-living calculator", eyebrow: "Feature 18 · Finance", description: "Estimate your monthly budget by city with a transparent, deterministic breakdown you can adjust.", group: "finance", category: "finance", icon: Coins, featureNo: 18, disclaimer: true, Component: FinanceCostOfLiving },
  { path: "/finance/health-insurance", label: "Health insurance", title: "Health-insurance selector", eyebrow: "Feature 19 · Finance", description: "Choose between statutory and private student health insurance — required for enrolment and the visa.", group: "finance", category: "finance", icon: HeartPulse, featureNo: 19, disclaimer: true, Component: FinanceHealthInsurance },
  { path: "/finance/scholarships", label: "Scholarship finder", title: "Scholarship finder", eyebrow: "Feature 20 · Finance", description: "Find scholarships you're eligible for — DAAD, Deutschlandstipendium, Erasmus+, and more.", group: "finance", category: "finance", icon: Award, featureNo: 20, disclaimer: true, Component: FinanceScholarships },
  { path: "/finance/work", label: "HiWi / Werkstudent", title: "HiWi & Werkstudent readiness", eyebrow: "Feature 21 · Finance", description: "Learn the rules and norms for student jobs in Germany, including legal working-hour limits.", group: "finance", category: "finance", icon: Briefcase, featureNo: 21, disclaimer: true, Component: FinanceWork },
  { path: "/visa", label: "Overview", title: "Visa & Relocation", eyebrow: "Bereich E · Visa & Relocation", description: "Get from offer letter to Anmeldung: APS, the student visa, accommodation, and registering your address.", group: "visa", category: "visa", icon: Plane, disclaimer: true, Component: VisaOverview },
  { path: "/visa/simulator", label: "Visa interview simulator", title: "Visa interview simulator", eyebrow: "Feature 22 · Visa", description: "Rehearse the student-visa interview with realistic questions and spoken practice.", group: "visa", category: "visa", icon: Mic, featureNo: 22, disclaimer: true, Component: VisaSimulator },
  { path: "/visa/checklist", label: "Visa checklist", title: "Visa checklist & deadlines", eyebrow: "Feature 23 · Visa", description: "The documents a German student-visa application needs, plus appointment lead times to plan around.", group: "visa", category: "visa", icon: ListChecks, featureNo: 23, disclaimer: true, Component: VisaChecklist },
  { path: "/visa/aps", label: "APS guide", title: "APS certificate guide", eyebrow: "Feature 24 · Visa", description: "Understand the Akademische Prüfstelle check required for students from some countries, and how to get it.", group: "visa", category: "visa", icon: Stamp, featureNo: 24, disclaimer: true, Component: VisaAps },
  { path: "/visa/accommodation", label: "Accommodation finder", title: "Accommodation finder", eyebrow: "Feature 25 · Visa", description: "Find student housing — Studierendenwerk dorms and the private market — and avoid common rental scams.", group: "visa", category: "visa", icon: Building2, featureNo: 25, disclaimer: true, Component: VisaAccommodation },
  { path: "/visa/anmeldung", label: "Anmeldung simulation", title: "Anmeldung (address registration)", eyebrow: "Feature 26 · Visa", description: "Walk through registering your address at the Bürgeramt after you arrive — the step that unlocks everything else.", group: "visa", category: "visa", icon: MapPin, featureNo: 26, disclaimer: true, Component: VisaAnmeldung },
  { path: "/campus", label: "Overview", title: "Campus Life", eyebrow: "Bereich F · Campus Life", description: "Land well: pre-departure packing, academic networking, transit, and how German academic culture works.", group: "campus", category: "campus", icon: Sparkles, Component: CampusOverview },
  { path: "/campus/pre-departure", label: "Pre-departure checklist", title: "Pre-departure checklist", eyebrow: "Feature 27 · Campus", description: "Everything to arrange and pack before you fly — documents, money, tech, and first-week essentials.", group: "campus", category: "campus", icon: Backpack, featureNo: 27, Component: CampusPreDeparture },
  { path: "/campus/networking", label: "Academic networking", title: "Academic networking", eyebrow: "Feature 28 · Campus", description: "Build relationships with professors, peers, and student groups — how to reach out and what to say.", group: "campus", category: "campus", icon: Users, featureNo: 28, Component: CampusNetworking },
  { path: "/campus/deutschlandticket", label: "Deutschlandticket guide", title: "Deutschlandticket guide", eyebrow: "Feature 29 · Campus", description: "Use Germany's nationwide public-transport ticket and the discounted student semester ticket.", group: "campus", category: "campus", icon: TramFront, featureNo: 29, Component: CampusDeutschlandticket },
  { path: "/campus/culture", label: "Academic culture", title: "Academic culture & plagiarism", eyebrow: "Feature 30 · Campus", description: "How German universities expect you to study, cite, and behave — including strict plagiarism rules.", group: "campus", category: "campus", icon: BookOpen, featureNo: 30, Component: CampusCulture },
  { path: "/about", label: "About & methodology", title: "About DeutschPrep", eyebrow: "Info · Methodik", description: "How DeutschPrep grounds official facts, computes deterministic values, and what it does not do.", group: "system", icon: Info, Component: AboutPage },
  { path: "/settings", label: "Profile & settings", title: "Profile & settings", eyebrow: "Einstellungen · Settings", description: "Manage the intake details that personalize your roadmap. Your data stays on this device in this build.", group: "system", icon: Settings, Component: SettingsPage },
  { path: "/help", label: "Help & FAQ", title: "Help & FAQ", eyebrow: "Hilfe · Help", description: "Answers to common questions, with the advisory disclaimer and links to official sources.", group: "system", icon: CircleHelp, Component: HelpPage },
  { path: "/legal/privacy", label: "Privacy Policy", title: "Privacy Policy", eyebrow: "Datenschutz · Privacy", description: "How DeutschPrep handles your personal data, including GDPR export and deletion.", group: "system", icon: ShieldCheck, hide: true, Component: PrivacyPage },
  { path: "/legal/terms", label: "Terms of Service", title: "Terms of Service", eyebrow: "Nutzungsbedingungen · Terms", description: "The terms for using DeutschPrep.", group: "system", icon: FileText, hide: true, Component: TermsPage },
  { path: "/legal/accessibility", label: "Accessibility", title: "Accessibility statement", eyebrow: "Barrierefreiheit · Accessibility", description: "Our commitment to WCAG 2.1 AA and how to report barriers.", group: "system", icon: Accessibility, hide: true, Component: AccessibilityPage },
  { path: "*", label: "Not found", title: "Page not found", eyebrow: "404", description: "That page doesn't exist. Use the navigation to get back on track.", group: "system", icon: FileSearch, hide: true, Component: NotFoundPage },
];

/** Visible nav items grouped in sidebar order. */
export function navByGroup(): { key: NavGroupKey; label: string; items: NavItem[] }[] {
  return (Object.keys(NAV_GROUPS) as NavGroupKey[]).map((key) => ({
    key,
    label: NAV_GROUPS[key],
    items: NAV.filter((n) => n.group === key && !n.hide),
  })).filter((g) => g.items.length > 0);
}

/** Look up a nav item by exact path. */
export function navItem(path: string): NavItem | undefined {
  return NAV.find((n) => n.path === path);
}
