/* AUTO-GENERATED by scripts/gen-pages.mjs — do not edit by hand.
 * Single source of truth for the route table: path, page metadata, lazy component, and nav grouping.
 * Re-run `node scripts/gen-pages.mjs` to regenerate after editing the PAGES list in that script. */
import { lazy, type ComponentType, type LazyExoticComponent } from "react";
import {
  Accessibility,
  Activity,
  Award,
  Backpack,
  BarChart3,
  BellRing,
  BookOpen,
  BookOpenCheck,
  Briefcase,
  Building2,
  Calculator,
  CalendarDays,
  CalendarRange,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Coins,
  Columns3,
  Compass,
  Eye,
  FileBadge,
  FileCheck,
  FileSearch,
  FileText,
  FolderCheck,
  FolderLock,
  Gauge,
  Globe,
  GraduationCap,
  Headphones,
  HeartPulse,
  Info,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Library,
  ListChecks,
  Map,
  MapPin,
  MessageSquare,
  Mic,
  PenLine,
  Plane,
  Route,
  ScanLine,
  School,
  ScrollText,
  Settings,
  ShieldCheck,
  Sigma,
  Sparkles,
  Stamp,
  Target,
  TramFront,
  TrendingUp,
  Trophy,
  UserCircle,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import type { FeatureCategoryKey } from "@/lib/types";

export type NavGroupKey =
  | "overview"
  | "start"
  | "career"
  | "profile"
  | "documents"
  | "language"
  | "finance"
  | "visa"
  | "arrival"
  | "campus"
  | "system";

export const NAV_GROUPS: Record<NavGroupKey, string> = {
  overview: "Overview",
  start: "Start Here",
  career: "Career & Guidance",
  profile: "Profile & Assessment",
  documents: "Document Prep",
  language: "Language & Test Prep",
  finance: "Finance & Logistics",
  visa: "Visa & Relocation",
  arrival: "Arrival & Settling In",
  campus: "Campus Life",
  system: "System",
};

export interface NavItem {
  path: string;
  label: string;
  title: string;
  eyebrow?: string;
  description?: string;
  group: NavGroupKey;
  category?: FeatureCategoryKey;
  icon: LucideIcon;
  /** 1–30 for the canonical features (feature-matrix.md). */
  featureNo?: number;
  /** Hidden from the sidebar (sub-pages, 404). */
  hide?: boolean;
  /** Requires the finance/visa advisory disclaimer. */
  disclaimer?: boolean;
  Component: LazyExoticComponent<ComponentType>;
}

const Dashboard = lazy(() => import("@/pages/overview/Dashboard"));
const RoadmapPage = lazy(() => import("@/pages/overview/Roadmap"));
const ProcessPage = lazy(() => import("@/pages/overview/Process"));
const DeadlinesPage = lazy(() => import("@/pages/overview/Deadlines"));
const EventsPage = lazy(() => import("@/pages/overview/Events"));
const DocumentsHubPage = lazy(() => import("@/pages/overview/DocumentsHub"));
const TimelinePage = lazy(() => import("@/pages/overview/Timeline"));
const SourcesPage = lazy(() => import("@/pages/overview/Sources"));
const TrackerPage = lazy(() => import("@/pages/overview/Tracker"));
const AdmissionLetterPage = lazy(() => import("@/pages/overview/AdmissionLetter"));
const OfferComparisonPage = lazy(() => import("@/pages/overview/OfferComparison"));
const SeatDeadlinesPage = lazy(() => import("@/pages/overview/SeatDeadlines"));
const CalendarPage = lazy(() => import("@/pages/overview/Calendar"));
const NextActionsPage = lazy(() => import("@/pages/overview/NextActions"));
const RemindersPage = lazy(() => import("@/pages/overview/Reminders"));
const LeaderboardPage = lazy(() => import("@/pages/overview/Leaderboard"));
const StartOverview = lazy(() => import("@/pages/start/Overview"));
const StartEligibility = lazy(() => import("@/pages/start/Eligibility"));
const StartFeasibility = lazy(() => import("@/pages/start/Feasibility"));
const StartTimelinePlanner = lazy(() => import("@/pages/start/TimelinePlanner"));
const StartBudget = lazy(() => import("@/pages/start/Budget"));
const CareerOverview = lazy(() => import("@/pages/career/Overview"));
const CareerCounseling = lazy(() => import("@/pages/career/Counseling"));
const CareerOutcomes = lazy(() => import("@/pages/career/Outcomes"));
const CareerEducationSystem = lazy(() => import("@/pages/career/EducationSystem"));
const ProfileOverview = lazy(() => import("@/pages/profile/Overview"));
const ProfileParse = lazy(() => import("@/pages/profile/Parse"));
const ProfileEvaluate = lazy(() => import("@/pages/profile/Evaluate"));
const ProfilePathway = lazy(() => import("@/pages/profile/Pathway"));
const ProfileMatching = lazy(() => import("@/pages/profile/Matching"));
const ProfileSkillGap = lazy(() => import("@/pages/profile/SkillGap"));
const ProfileEcts = lazy(() => import("@/pages/profile/Ects"));
const ProfileShortlist = lazy(() => import("@/pages/profile/Shortlist"));
const ProfileSupervisors = lazy(() => import("@/pages/profile/Supervisors"));
const ProfileCities = lazy(() => import("@/pages/profile/Cities"));
const UniversitiesExplorer = lazy(() => import("@/pages/profile/Universities"));
const ProfileRecognition = lazy(() => import("@/pages/profile/Recognition"));
const ProfileStudienkolleg = lazy(() => import("@/pages/profile/Studienkolleg"));
const DocumentsOverview = lazy(() => import("@/pages/documents/Overview"));
const DocumentsSop = lazy(() => import("@/pages/documents/Sop"));
const DocumentsCv = lazy(() => import("@/pages/documents/Cv"));
const DocumentsLor = lazy(() => import("@/pages/documents/Lor"));
const DocumentsUniAssist = lazy(() => import("@/pages/documents/UniAssist"));
const DocumentsVpd = lazy(() => import("@/pages/documents/Vpd"));
const DocumentsTranslation = lazy(() => import("@/pages/documents/Translation"));
const DocumentsLorTracker = lazy(() => import("@/pages/documents/LorTracker"));
const DocumentsTranslationTracker = lazy(() => import("@/pages/documents/TranslationTracker"));
const DocumentsAttestation = lazy(() => import("@/pages/documents/Attestation"));
const DocumentsVpdHelper = lazy(() => import("@/pages/documents/VpdHelper"));
const DocumentsDosv = lazy(() => import("@/pages/documents/Dosv"));
const DocumentsRequirements = lazy(() => import("@/pages/documents/Requirements"));
const DocumentsVaultMatrix = lazy(() => import("@/pages/documents/VaultMatrix"));
const DocumentsVault = lazy(() => import("@/pages/documents/Vault"));
const LanguageOverview = lazy(() => import("@/pages/language/Overview"));
const LanguageGerman = lazy(() => import("@/pages/language/German"));
const LanguageFlashcards = lazy(() => import("@/pages/language/Flashcards"));
const LanguageIeltsToefl = lazy(() => import("@/pages/language/IeltsToefl"));
const LanguageGreGmat = lazy(() => import("@/pages/language/GreGmat"));
const LanguageGoetheTestdaf = lazy(() => import("@/pages/language/GoetheTestdaf"));
const LanguageGermanPlan = lazy(() => import("@/pages/language/GermanPlan"));
const LanguageTestAs = lazy(() => import("@/pages/language/TestAs"));
const LanguageDsh = lazy(() => import("@/pages/language/Dsh"));
const LanguagePlacement = lazy(() => import("@/pages/language/Placement"));
const LanguageAufnahmepruefung = lazy(() => import("@/pages/language/Aufnahmepruefung"));
const LanguageFsp = lazy(() => import("@/pages/language/Fsp"));
const LanguageTms = lazy(() => import("@/pages/language/Tms"));
const LanguageExamsHub = lazy(() => import("@/pages/language/ExamsHub"));
const LanguageExamTracker = lazy(() => import("@/pages/language/ExamTracker"));
const ExamIelts = lazy(() => import("@/pages/language/exams/Ielts"));
const ExamToefl = lazy(() => import("@/pages/language/exams/Toefl"));
const ExamToeflLegacy = lazy(() => import("@/pages/language/exams/ToeflLegacy"));
const ExamTestdaf = lazy(() => import("@/pages/language/exams/Testdaf"));
const ExamGoethe = lazy(() => import("@/pages/language/exams/Goethe"));
const ExamGre = lazy(() => import("@/pages/language/exams/Gre"));
const ExamGmat = lazy(() => import("@/pages/language/exams/Gmat"));
const FinanceOverview = lazy(() => import("@/pages/finance/Overview"));
const FinanceSperrkonto = lazy(() => import("@/pages/finance/Sperrkonto"));
const FinanceCostOfLiving = lazy(() => import("@/pages/finance/CostOfLiving"));
const FinanceHealthInsurance = lazy(() => import("@/pages/finance/HealthInsurance"));
const FinanceScholarships = lazy(() => import("@/pages/finance/Scholarships"));
const FinanceWork = lazy(() => import("@/pages/finance/Work"));
const FinanceWorkDays = lazy(() => import("@/pages/finance/WorkDays"));
const FinanceApplicationCosts = lazy(() => import("@/pages/finance/ApplicationCosts"));
const FinanceScholarshipTracker = lazy(() => import("@/pages/finance/ScholarshipTracker"));
const FinanceFundingPlan = lazy(() => import("@/pages/finance/FundingPlan"));
const FinanceLoans = lazy(() => import("@/pages/finance/Loans"));
const FinanceSperrkontoProviders = lazy(() => import("@/pages/finance/SperrkontoProviders"));
const VisaOverview = lazy(() => import("@/pages/visa/Overview"));
const VisaSimulator = lazy(() => import("@/pages/visa/Simulator"));
const VisaChecklist = lazy(() => import("@/pages/visa/Checklist"));
const VisaAppointment = lazy(() => import("@/pages/visa/Appointment"));
const VisaType = lazy(() => import("@/pages/visa/VisaType"));
const VisaVidex = lazy(() => import("@/pages/visa/Videx"));
const VisaAps = lazy(() => import("@/pages/visa/Aps"));
const VisaAccommodation = lazy(() => import("@/pages/visa/Accommodation"));
const VisaAnmeldung = lazy(() => import("@/pages/visa/Anmeldung"));
const ArrivalOverview = lazy(() => import("@/pages/arrival/Overview"));
const ArrivalEnrolment = lazy(() => import("@/pages/arrival/Enrolment"));
const ArrivalBankAccount = lazy(() => import("@/pages/arrival/BankAccount"));
const ArrivalResidencePermit = lazy(() => import("@/pages/arrival/ResidencePermit"));
const ArrivalAuslaenderbehoerde = lazy(() => import("@/pages/arrival/Auslaenderbehoerde"));
const ArrivalUniversityOnboarding = lazy(() => import("@/pages/arrival/UniversityOnboarding"));
const ArrivalAnmeldungRunbook = lazy(() => import("@/pages/arrival/AnmeldungRunbook"));
const ArrivalRundfunkbeitrag = lazy(() => import("@/pages/arrival/Rundfunkbeitrag"));
const ArrivalJobSeekerPermit = lazy(() => import("@/pages/arrival/JobSeekerPermit"));
const ArrivalFamilyReunion = lazy(() => import("@/pages/arrival/FamilyReunion"));
const ArrivalRenewals = lazy(() => import("@/pages/arrival/Renewals"));
const ArrivalArrivalDay = lazy(() => import("@/pages/arrival/ArrivalDay"));
const ArrivalBlueCard = lazy(() => import("@/pages/arrival/BlueCard"));
const ArrivalImmigrationPathway = lazy(() => import("@/pages/arrival/ImmigrationPathway"));
const ArrivalBlueCardCheck = lazy(() => import("@/pages/arrival/BlueCardCheck"));
const ArrivalPrCitizenship = lazy(() => import("@/pages/arrival/PrCitizenship"));
const ArrivalTaxId = lazy(() => import("@/pages/arrival/TaxId"));
const CampusOverview = lazy(() => import("@/pages/campus/Overview"));
const CampusPreDeparture = lazy(() => import("@/pages/campus/PreDeparture"));
const CampusNetworking = lazy(() => import("@/pages/campus/Networking"));
const CampusDeutschlandticket = lazy(() => import("@/pages/campus/Deutschlandticket"));
const CampusCulture = lazy(() => import("@/pages/campus/Culture"));
const AboutPage = lazy(() => import("@/pages/system/About"));
const SettingsPage = lazy(() => import("@/pages/system/Settings"));
const HelpPage = lazy(() => import("@/pages/system/Help"));
const PrivacyPage = lazy(() => import("@/pages/system/Privacy"));
const TermsPage = lazy(() => import("@/pages/system/Terms"));
const AccessibilityPage = lazy(() => import("@/pages/system/Accessibility"));
const NotFoundPage = lazy(() => import("@/pages/system/NotFound"));

export const NAV: NavItem[] = [
  { path: "/", label: "Dashboard", title: "Application dashboard", eyebrow: "Übersicht · Overview", description: "Your German Master's application at a glance — profile, roadmap, deadlines, and progress across all six areas.", group: "overview", icon: LayoutDashboard, Component: Dashboard },
  { path: "/roadmap", label: "Roadmap", title: "Step-by-step roadmap", eyebrow: "Aktenplan · Roadmap", description: "A dependency-ordered plan from profile evaluation to enrolment. Each step links to the tool that completes it.", group: "overview", icon: Map, Component: RoadmapPage },
  { path: "/process", label: "Application status", title: "Application status board", eyebrow: "Bearbeitungsstand · Status", description: "Process polling for every application thread — where each one stands in the not-started → submitted → complete pipeline.", group: "overview", icon: Activity, Component: ProcessPage },
  { path: "/deadlines", label: "Deadlines & alerts", title: "Deadlines & alerts", eyebrow: "Fristen · Deadlines", description: "Every date that matters, soonest first, with urgency computed deterministically. Official dates that change yearly are flagged for verification.", group: "overview", icon: BellRing, Component: DeadlinesPage },
  { path: "/events", label: "Event watch", title: "Event watch", eyebrow: "Terminüberwachung · Event watch", description: "Recurring windows worth watching — portal openings, intake cycles, scholarship rounds, and visa-appointment lead times.", group: "overview", icon: Eye, Component: EventsPage },
  { path: "/documents-checklist", label: "Document gathering", title: "Document gathering", eyebrow: "Unterlagen · Documents", description: "Master checklists for the whole journey: application, APS, visa, and enrolment paperwork — with where to obtain each.", group: "overview", icon: FolderCheck, Component: DocumentsHubPage },
  { path: "/timeline", label: "Timeline", title: "Preparation timeline", eyebrow: "Zeitplan · Timeline", description: "A month-by-month view of the typical 12–18 month preparation arc, from first research to arrival in Germany.", group: "overview", icon: CalendarRange, Component: TimelinePage },
  { path: "/sources", label: "Sources", title: "Source registry", eyebrow: "Quellen · Sources", description: "Every official source DeutschPrep cites. Specific figures are grounded against these or flagged for verification.", group: "overview", icon: Library, Component: SourcesPage },
  { path: "/tracker", label: "Application tracker", title: "Application tracker", eyebrow: "Bewerbungen · Tracker", description: "A Kanban board of every programme you're applying to — from researching to decision. Syncs to your account.", group: "overview", icon: Columns3, Component: TrackerPage },
  { path: "/offers/interpret", label: "Admission-letter interpreter", title: "Admission letter (Zulassungsbescheid) interpreter", eyebrow: "G25 · Offers", description: "Decode your admission letter: what's conditional, the enrolment deadline you can't miss, and the exact next actions it triggers.", group: "overview", icon: FileBadge, Component: AdmissionLetterPage },
  { path: "/offers/compare", label: "Offer comparison board", title: "Offer comparison board", eyebrow: "G26 · Offers", description: "Hold multiple admits side by side — cost, city, language, deadline — and decide with a clear head instead of a dozen browser tabs.", group: "overview", icon: Columns3, Component: OfferComparisonPage },
  { path: "/offers/seat-deadlines", label: "Seat-acceptance deadlines", title: "Seat-acceptance deadline tracker", eyebrow: "G28 · Offers", description: "Accepting a seat has its own hard deadline, separate from the application. Track each offer's accept-by date so you never lose a place.", group: "overview", icon: BellRing, Component: SeatDeadlinesPage },
  { path: "/calendar", label: "Deadline calendar", title: "Deadline calendar", eyebrow: "Kalender · Calendar", description: "Every application, VPD, visa, and Sperrkonto date on a month grid — plus deadlines you add yourself.", group: "overview", icon: CalendarDays, Component: CalendarPage },
  { path: "/next-actions", label: "Your next 3 actions", title: "You are here — your next 3 actions", eyebrow: "G50 · Overview", description: "One screen that reads your pathway and profile and tells you the single most useful thing to do next — and the two after it.", group: "overview", icon: Target, Component: NextActionsPage },
  { path: "/reminders", label: "Reminders & calendar export", title: "Reminders & calendar export", eyebrow: "G51 · Overview", description: "All your personal deadlines in one place, with a one-click calendar (.ics) export so your reminders live in the app you already check.", group: "overview", icon: BellRing, Component: RemindersPage },
  { path: "/leaderboard", label: "Leaderboard", title: "Your standing", eyebrow: "Rangliste · Leaderboard", description: "See how your readiness, roadmap progress, mock bands, and streak compare — anonymously — against everyone else preparing. Opt in to a pseudonymous board.", group: "overview", icon: Trophy, Component: LeaderboardPage },
  { path: "/start", label: "Start here", title: "Start here — orient yourself in 5 minutes", eyebrow: "Phase 0 · Orientation", description: "New to studying in Germany? Four quick tools to learn whether you're eligible, by which route, by when, and at what total cost — before you invest in the full plan.", group: "start", icon: Compass, Component: StartOverview },
  { path: "/start/eligibility", label: "Eligibility quick-check", title: "Am I eligible? — 30-second check", eyebrow: "Phase 0 · Orientation", description: "Answer four questions and see whether — and by which route (direct Bachelor, Studienkolleg, Master, Medicine) — you can study in Germany. No signup, deterministic, grounded rules to verify.", group: "start", icon: ClipboardCheck, Component: StartEligibility },
  { path: "/start/feasibility", label: "Reality check", title: "Reality check — feasibility & years to finish", eyebrow: "Phase 0 · Orientation", description: "A blunt, honest read on how realistic your plan is and roughly how long it takes end-to-end, given your level, language, and target. A heuristic, not a guarantee.", group: "start", icon: Gauge, Component: StartFeasibility },
  { path: "/start/timeline-planner", label: "Reverse timeline planner", title: "Reverse timeline — work back from your intake", eyebrow: "Phase 0 · Orientation", description: "Pick a target intake and we back-date every milestone — language tests, APS, applications, visa, Sperrkonto — so you know what to start by when.", group: "start", icon: CalendarRange, Component: StartTimelinePlanner },
  { path: "/start/budget", label: "Total-journey budget", title: "Total-journey budget — one-time + recurring", eyebrow: "Phase 0 · Orientation", description: "Add up the real end-to-end cost: APS, uni-assist, translations, visa, Sperrkonto, flights, deposit, and monthly living — with every official figure grounded or flagged.", group: "start", icon: Calculator, disclaimer: true, Component: StartBudget },
  { path: "/career", label: "Career & guidance", title: "Career & guidance", eyebrow: "Bereich · Career", description: "Before you pick a programme, figure out the right direction: counseling, course selection, the German education system, and where each field actually leads in the job market.", group: "career", icon: Compass, Component: CareerOverview },
  { path: "/career/counseling", label: "Counseling & course choice", title: "Career counseling & course selection", eyebrow: "§ Counseling", description: "A short interest self-check plus optional AI consultation turns your background and interests into German programme fields to explore — then feeds straight into university matching.", group: "career", icon: MessageSquare, Component: CareerCounseling },
  { path: "/career/outcomes", label: "Career outcomes & demand", title: "Career outcomes & job market", eyebrow: "§ Outcomes", description: "What each field leads to in Germany — typical roles, demand, shortage-occupation status, and which EU Blue Card threshold it maps to. Qualitative + grounded; no invented salaries.", group: "career", icon: TrendingUp, Component: CareerOutcomes },
  { path: "/career/education-system", label: "German education system", title: "How the German education system works", eyebrow: "§ Orientation", description: "Universität vs Technische Universität vs Fachhochschule (FH), and the school structure behind the HZB — so recognition and your options make sense.", group: "career", icon: School, Component: CareerEducationSystem },
  { path: "/profile", label: "Overview", title: "Profile & Assessment", eyebrow: "Bereich A · Profile & Assessment", description: "Turn your resume into a German-readable academic profile: parsed facts, a converted grade, matched programs, and skill gaps.", group: "profile", category: "profile", icon: UserCircle, Component: ProfileOverview },
  { path: "/profile/parse", label: "Resume / LinkedIn parsing", title: "Resume & LinkedIn parsing", eyebrow: "Feature 01 · Profile", description: "Extract structured facts from a resume, LinkedIn export, or intake form — handled as personal data.", group: "profile", category: "profile", icon: ScanLine, featureNo: 1, Component: ProfileParse },
  { path: "/profile/evaluate", label: "Profile evaluation (GPA)", title: "Profile evaluation — GPA → German grade", eyebrow: "Feature 02 · Profile", description: "Convert your grade to the German 1.0–4.0 scale with the deterministic Modified Bavarian Formula.", group: "profile", category: "profile", icon: Gauge, featureNo: 2, Component: ProfileEvaluate },
  { path: "/profile/pathway", label: "Study pathway", title: "Your German study pathway", eyebrow: "Pfad · Pathway", description: "Bachelor, Master, Medicine or Studienkolleg — the correct German route for your level and country, with honest next steps and grounded rules to verify.", group: "profile", category: "profile", icon: Route, Component: ProfilePathway },
  { path: "/profile/matching", label: "University matching", title: "Course & university matching", eyebrow: "Feature 03 · Profile", description: "Shortlist Master's programs at German public universities that fit your background and goals.", group: "profile", category: "profile", icon: GraduationCap, featureNo: 3, Component: ProfileMatching },
  { path: "/profile/skill-gap", label: "Skill-gap analysis", title: "Skill-gap analysis", eyebrow: "Feature 04 · Profile", description: "See what target programs expect that your profile doesn't yet show — and how to close each gap.", group: "profile", category: "profile", icon: Target, featureNo: 4, Component: ProfileSkillGap },
  { path: "/profile/ects", label: "ECTS calculator", title: "ECTS calculator", eyebrow: "Feature 05 · Profile", description: "Total and normalize your credits to ECTS so admissions can compare your degree to a German one.", group: "profile", category: "profile", icon: Calculator, featureNo: 5, Component: ProfileEcts },
  { path: "/profile/shortlist", label: "Reach / match / safety", title: "Reach / match / safety shortlist", eyebrow: "G14 · Profile", description: "Balance your programme list into ambitious, realistic, and safe tiers using your honest per-programme eligibility — so you don't over-bet on long shots.", group: "profile", category: "profile", icon: Target, Component: ProfileShortlist },
  { path: "/profile/supervisors", label: "Supervisor / lab finder", title: "Professor & research-group outreach", eyebrow: "G16 · Profile", description: "For PhD and research-track applicants: how to find and approach a supervisor, with a tracker for your outreach.", group: "profile", category: "profile", icon: Users, Component: ProfileSupervisors },
  { path: "/profile/cities", label: "City explorer", title: "City explorer — where to study & live", eyebrow: "G17 · Profile", description: "Compare student cities on the factors that matter — rough rent, size, and what to research — before you commit to a programme's location.", group: "profile", category: "profile", icon: MapPin, Component: ProfileCities },
  { path: "/universities", label: "Universities explorer", title: "Universities & programs explorer", eyebrow: "Hochschulen · Universities", description: "Browse and compare Master's programmes at German public universities, with grounded requirements you can re-verify.", group: "profile", category: "profile", icon: School, Component: UniversitiesExplorer },
  { path: "/profile/recognition", label: "Recognition (anabin / HZB)", title: "Qualification recognition — anabin & HZB", eyebrow: "G05 · Foundations", description: "Understand how your certificates are recognised in Germany (the HZB categories), and look up the binding status on anabin — we orient you, anabin decides.", group: "profile", category: "profile", icon: FileBadge, Component: ProfileRecognition },
  { path: "/profile/studienkolleg", label: "Studienkolleg finder", title: "Studienkolleg finder & course (Kurs) guide", eyebrow: "G06 · Foundations", description: "If your school-leaving certificate isn't Abitur-equivalent, the Studienkolleg is your route. Find the right course stream and how to apply through a university.", group: "profile", category: "profile", icon: Library, Component: ProfileStudienkolleg },
  { path: "/documents", label: "Overview", title: "Document Prep", eyebrow: "Bereich B · Document Prep", description: "Draft and track every document an application needs: SOP, CV, recommendation letters, and the uni-assist workflow.", group: "documents", category: "documents", icon: FileText, Component: DocumentsOverview },
  { path: "/documents/sop", label: "Statement of Purpose", title: "Statement of Purpose generator", eyebrow: "Feature 06 · Documents", description: "Build a tailored SOP from your profile and a target program — structured, specific, and yours to edit.", group: "documents", category: "documents", icon: PenLine, featureNo: 6, Component: DocumentsSop },
  { path: "/documents/cv", label: "Europass CV", title: "Europass CV builder", eyebrow: "Feature 07 · Documents", description: "Produce a Europass-format CV, the European standard German universities recognize.", group: "documents", category: "documents", icon: FileBadge, featureNo: 7, Component: DocumentsCv },
  { path: "/documents/lor", label: "Recommendation letters", title: "Letter of Recommendation templates", eyebrow: "Feature 08 · Documents", description: "Give recommenders a strong starting draft tailored to the program and your relationship.", group: "documents", category: "documents", icon: ScrollText, featureNo: 8, Component: DocumentsLor },
  { path: "/documents/uni-assist", label: "Uni-Assist walkthrough", title: "Uni-Assist walkthrough", eyebrow: "Feature 09 · Documents", description: "Step through the uni-assist application: account, programs, documents, fees, and what happens after you submit.", group: "documents", category: "documents", icon: ClipboardList, featureNo: 9, Component: DocumentsUniAssist },
  { path: "/documents/vpd", label: "VPD tracker", title: "VPD (Preliminary Documentation) tracker", eyebrow: "Feature 10 · Documents", description: "Track the Vorprüfungsdokumentation some universities require before you apply directly.", group: "documents", category: "documents", icon: FileCheck, featureNo: 10, Component: DocumentsVpd },
  { path: "/documents/translation", label: "Translation assistant", title: "Translation assistant", eyebrow: "Feature 11 · Documents", description: "Understand which documents need certified translations and prepare drafts to hand to a sworn translator.", group: "documents", category: "documents", icon: Languages, featureNo: 11, Component: DocumentsTranslation },
  { path: "/documents/lor-tracker", label: "LOR request tracker", title: "Recommendation-letter request tracker", eyebrow: "G20 · Documents", description: "The ask-to-receive workflow your LOR drafts don't cover: who you asked, when, deadlines, and whether each letter is in.", group: "documents", category: "documents", icon: ScrollText, Component: DocumentsLorTracker },
  { path: "/documents/translation-tracker", label: "Translation tracker", title: "Certified-translation tracker", eyebrow: "G21 · Documents", description: "Per-document status of your certified translations — which sworn translator, cost, and whether each is back.", group: "documents", category: "documents", icon: Languages, Component: DocumentsTranslationTracker },
  { path: "/documents/attestation", label: "Attestation & legalization", title: "Attestation & legalization tracker", eyebrow: "G22 · Documents", description: "Certified copies, notarisation, and apostille/legalisation — track which documents are authenticated and which still need it.", group: "documents", category: "documents", icon: FileCheck, Component: DocumentsAttestation },
  { path: "/documents/vpd-helper", label: "VPD-or-direct helper", title: "VPD or direct application — decision helper", eyebrow: "G23 · Documents", description: "Some universities want a uni-assist VPD, others a direct application. Answer a couple of questions to see which path applies to you.", group: "documents", category: "documents", icon: FileSearch, Component: DocumentsVpdHelper },
  { path: "/documents/dosv", label: "DoSV / hochschulstart", title: "DoSV / hochschulstart walkthrough", eyebrow: "G24 · Documents", description: "For NC Bachelor and Medicine places allocated centrally, you apply via hochschulstart's DoSV. Walk through the priorities and the dialogue-oriented procedure.", group: "documents", category: "documents", icon: ClipboardList, Component: DocumentsDosv },
  { path: "/documents/requirements", label: "Per-programme requirements", title: "Per-programme requirement capture", eyebrow: "G15 · Documents", description: "Paste each programme's stated requirements into a structured, persisted record so you stop re-reading portals and can see what's still missing.", group: "documents", category: "documents", icon: FileSearch, Component: DocumentsRequirements },
  { path: "/documents/vault-matrix", label: "Doc-per-application matrix", title: "Which document went to which application", eyebrow: "G19 · Documents", description: "A matrix of your core documents against each application, so you always know what's been sent where and what's still outstanding.", group: "documents", category: "documents", icon: FolderCheck, Component: DocumentsVaultMatrix },
  { path: "/vault", label: "Document vault", title: "Document vault", eyebrow: "Tresor · Vault", description: "One place for your SOP, CV, recommendation letters, transcripts, and certificates — synced to your account.", group: "documents", category: "documents", icon: FolderLock, Component: DocumentsVault },
  { path: "/language", label: "Overview", title: "Language & Test Prep", eyebrow: "Bereich C · Language & Test", description: "Reach the German or English level your program requires, and rehearse every admission test with timed mocks.", group: "language", category: "language", icon: Languages, Component: LanguageOverview },
  { path: "/language/german", label: "German A1–B2 (+TTS)", title: "German A1–B2 course", eyebrow: "Feature 12 · Language", description: "A structured path from beginner to B2, with audio practice for listening and pronunciation.", group: "language", category: "language", icon: BookOpen, featureNo: 12, Component: LanguageGerman },
  { path: "/language/flashcards", label: "SRS flashcards", title: "Spaced-repetition flashcards", eyebrow: "Feature 13 · Language", description: "Memorize vocabulary efficiently with a spaced-repetition schedule that surfaces cards right before you'd forget them.", group: "language", category: "language", icon: Layers, featureNo: 13, Component: LanguageFlashcards },
  { path: "/language/ielts-toefl", label: "IELTS / TOEFL prep", title: "IELTS & TOEFL preparation", eyebrow: "Feature 14 · Language", description: "Understand the formats, target the right band/score, and practice with timed section mocks.", group: "language", category: "language", icon: Headphones, featureNo: 14, Component: LanguageIeltsToefl },
  { path: "/language/gre-gmat", label: "GRE / GMAT checker", title: "GRE / GMAT requirement checker", eyebrow: "Feature 15 · Language", description: "Find out whether your target programs require GRE or GMAT, and what scores are competitive.", group: "language", category: "language", icon: BarChart3, featureNo: 15, Component: LanguageGreGmat },
  { path: "/language/goethe-testdaf", label: "Goethe / TestDaF guides", title: "Goethe & TestDaF guides", eyebrow: "Feature 16 · Language", description: "Pick the right German certificate (TestDaF, DSH, Goethe, telc) and prepare for each section.", group: "language", category: "language", icon: BookOpenCheck, featureNo: 16, Component: LanguageGoetheTestdaf },
  { path: "/language/german-plan", label: "German A1→C1 study plan", title: "German A1→C1 — structured study plan", eyebrow: "G09 · Language", description: "A level-by-level plan from absolute beginner to the C1 many German-taught degrees need — with realistic hours, milestones, and progress you can track.", group: "language", category: "language", icon: BookOpen, Component: LanguageGermanPlan },
  { path: "/language/testas", label: "TestAS prep", title: "TestAS — Test for Academic Studies", eyebrow: "G11 · Language", description: "Many Bachelor and foundation routes for international applicants expect TestAS. Understand the core + subject modules and how to prepare.", group: "language", category: "language", icon: ClipboardCheck, Component: LanguageTestAs },
  { path: "/language/dsh", label: "DSH exam prep", title: "DSH — university German exam", eyebrow: "G13 · Language", description: "The university-run C1 German exam (alongside TestDaF). Understand the DSH-1/2/3 levels, the sections, and how to prepare.", group: "language", category: "language", icon: BookOpenCheck, Component: LanguageDsh },
  { path: "/language/placement", label: "German placement self-check", title: "German level — quick self-check", eyebrow: "G10 · Language", description: "Estimate your current CEFR level from a short self-assessment, so you start your German plan at the right place instead of guessing.", group: "language", category: "language", icon: Gauge, Component: LanguagePlacement },
  { path: "/language/aufnahmepruefung", label: "Aufnahmeprüfung prep", title: "Studienkolleg entrance exam (Aufnahmeprüfung)", eyebrow: "G07 · Language", description: "The entrance test that gets you into a Studienkolleg — German plus subject basics. Know the format and how to prepare.", group: "language", category: "language", icon: ClipboardCheck, Component: LanguageAufnahmepruefung },
  { path: "/language/fsp", label: "FSP (Feststellungsprüfung) prep", title: "Feststellungsprüfung (FSP) prep", eyebrow: "G08 · Language", description: "The exam that confers your HZB at the end of the Studienkolleg — subjects, structure, and a per-subject prep tracker.", group: "language", category: "language", icon: BookOpenCheck, Component: LanguageFsp },
  { path: "/language/tms", label: "TMS (medicine) prep", title: "TMS — medical studies aptitude test", eyebrow: "G12 · Language", description: "The Test für Medizinische Studiengänge can lift your Medicine application. Understand the subtests and how to prepare.", group: "language", category: "language", icon: HeartPulse, Component: LanguageTms },
  { path: "/language/exams", label: "Mock exams", title: "Mock exam centre", eyebrow: "Übungstests · Mock exams", description: "Timed practice exams for every test you might need: IELTS, TOEFL, TestDaF, Goethe, GRE, and GMAT.", group: "language", category: "language", icon: ClipboardCheck, Component: LanguageExamsHub },
  { path: "/language/exam-progress", label: "Exam progress", title: "Exam progress & analytics", eyebrow: "Fortschritt · Progress", description: "Track your mock-exam scores over time: per-skill and per-question-type accuracy, ranked weaknesses, a predicted band, and a personalised study plan.", group: "language", category: "language", icon: TrendingUp, Component: LanguageExamTracker },
  { path: "/language/exams/ielts", label: "IELTS mock", title: "IELTS Academic — practice exam", eyebrow: "Übungstest · IELTS", description: "A timed IELTS Academic practice set across Listening, Reading, and Writing question types.", group: "language", category: "language", icon: Headphones, hide: true, Component: ExamIelts },
  { path: "/language/exams/toefl", label: "TOEFL mock", title: "TOEFL iBT — practice exam", eyebrow: "Übungstest · TOEFL", description: "A timed TOEFL iBT practice set across Reading and Listening question types.", group: "language", category: "language", icon: Globe, hide: true, Component: ExamToefl },
  { path: "/language/exams/toefl-legacy", label: "TOEFL legacy mock", title: "TOEFL iBT (legacy 0–120) — practice exam", eyebrow: "Übungstest · TOEFL legacy", description: "Practice the retired pre-2026 TOEFL format and interpret an old 0–120 score.", group: "language", category: "language", icon: Globe, hide: true, Component: ExamToeflLegacy },
  { path: "/language/exams/testdaf", label: "TestDaF mock", title: "TestDaF — practice exam", eyebrow: "Übungstest · TestDaF", description: "A timed TestDaF practice set mapped to the TDN 3–5 band scale.", group: "language", category: "language", icon: Languages, hide: true, Component: ExamTestdaf },
  { path: "/language/exams/goethe", label: "Goethe mock", title: "Goethe-Zertifikat — practice exam", eyebrow: "Übungstest · Goethe", description: "A timed CEFR-aligned German practice set (A2–B2 grammar, vocabulary, and reading).", group: "language", category: "language", icon: MessageSquare, hide: true, Component: ExamGoethe },
  { path: "/language/exams/gre", label: "GRE mock", title: "GRE General — practice exam", eyebrow: "Übungstest · GRE", description: "A timed GRE practice set across Verbal Reasoning and Quantitative Reasoning question types.", group: "language", category: "language", icon: Sigma, hide: true, Component: ExamGre },
  { path: "/language/exams/gmat", label: "GMAT mock", title: "GMAT Focus — practice exam", eyebrow: "Übungstest · GMAT", description: "A timed GMAT Focus practice set across Quantitative, Verbal, and Data Insights question types.", group: "language", category: "language", icon: TrendingUp, hide: true, Component: ExamGmat },
  { path: "/finance", label: "Overview", title: "Finance & Logistics", eyebrow: "Bereich D · Finance & Logistics", description: "Plan the money side: blocked account, monthly costs, health insurance, scholarships, and part-time work.", group: "finance", category: "finance", icon: Wallet, disclaimer: true, Component: FinanceOverview },
  { path: "/finance/sperrkonto", label: "Sperrkonto guide", title: "Blocked account (Sperrkonto) guide", eyebrow: "Feature 17 · Finance", description: "Understand the blocked account you need for the visa: how it works, the required amount, and which providers to use.", group: "finance", category: "finance", icon: Landmark, featureNo: 17, disclaimer: true, Component: FinanceSperrkonto },
  { path: "/finance/cost-of-living", label: "Cost-of-living calc", title: "Cost-of-living calculator", eyebrow: "Feature 18 · Finance", description: "Estimate your monthly budget by city with a transparent, deterministic breakdown you can adjust.", group: "finance", category: "finance", icon: Coins, featureNo: 18, disclaimer: true, Component: FinanceCostOfLiving },
  { path: "/finance/health-insurance", label: "Health insurance", title: "Health-insurance selector", eyebrow: "Feature 19 · Finance", description: "Choose between statutory and private student health insurance — required for enrolment and the visa.", group: "finance", category: "finance", icon: HeartPulse, featureNo: 19, disclaimer: true, Component: FinanceHealthInsurance },
  { path: "/finance/scholarships", label: "Scholarship finder", title: "Scholarship finder", eyebrow: "Feature 20 · Finance", description: "Find scholarships you're eligible for — DAAD, Deutschlandstipendium, Erasmus+, and more.", group: "finance", category: "finance", icon: Award, featureNo: 20, disclaimer: true, Component: FinanceScholarships },
  { path: "/finance/work", label: "HiWi / Werkstudent", title: "HiWi & Werkstudent readiness", eyebrow: "Feature 21 · Finance", description: "Learn the rules and norms for student jobs in Germany, including legal working-hour limits.", group: "finance", category: "finance", icon: Briefcase, featureNo: 21, disclaimer: true, Component: FinanceWork },
  { path: "/finance/work-days", label: "Work-day limit tracker", title: "Work-day limit tracker (140 / 280)", eyebrow: "G33 · Finance", description: "Log your working days against the annual 140-full / 280-half-day limit for non-EU students, computed deterministically so you never breach your permit.", group: "finance", category: "finance", icon: Briefcase, disclaimer: true, Component: FinanceWorkDays },
  { path: "/finance/application-costs", label: "Application-cost estimator", title: "Application-cost estimator", eyebrow: "G18 · Finance", description: "Sum the uni-assist and APS fees across your whole shortlist before you apply, so the application phase doesn't surprise you.", group: "finance", category: "finance", icon: Coins, disclaimer: true, Component: FinanceApplicationCosts },
  { path: "/finance/scholarship-tracker", label: "Scholarship tracker", title: "Scholarship application tracker", eyebrow: "G31 · Finance", description: "Track every scholarship you're applying to — deadline, status, and outcome — so none slips through.", group: "finance", category: "finance", icon: Award, disclaimer: true, Component: FinanceScholarshipTracker },
  { path: "/finance/funding-plan", label: "Funding-gap planner", title: "Funding-gap & affordability planner", eyebrow: "G32 · Finance", description: "Put your savings, family support, loan, scholarship, and expected work income against the total cost — and see, deterministically, whether you're covered.", group: "finance", category: "finance", icon: Coins, disclaimer: true, Component: FinanceFundingPlan },
  { path: "/finance/loans", label: "Education-loan comparison", title: "Education-loan comparison framework", eyebrow: "G29 · Finance", description: "The #1 funding route for many students. Compare loan offers on the terms that actually matter — without us inventing any rates.", group: "finance", category: "finance", icon: Landmark, disclaimer: true, Component: FinanceLoans },
  { path: "/finance/sperrkonto-providers", label: "Sperrkonto providers", title: "Sperrkonto provider comparison", eyebrow: "G30 · Finance", description: "Compare blocked-account providers on setup time, fees, and acceptance — and track your own funding progress toward the required amount.", group: "finance", category: "finance", icon: Landmark, disclaimer: true, Component: FinanceSperrkontoProviders },
  { path: "/visa", label: "Overview", title: "Visa & Relocation", eyebrow: "Bereich E · Visa & Relocation", description: "Get from offer letter to Anmeldung: APS, the student visa, accommodation, and registering your address.", group: "visa", category: "visa", icon: Plane, disclaimer: true, Component: VisaOverview },
  { path: "/visa/simulator", label: "Visa interview simulator", title: "Visa interview simulator", eyebrow: "Feature 22 · Visa", description: "Rehearse the student-visa interview with realistic questions and spoken practice.", group: "visa", category: "visa", icon: Mic, featureNo: 22, disclaimer: true, Component: VisaSimulator },
  { path: "/visa/checklist", label: "Visa checklist", title: "Visa checklist & deadlines", eyebrow: "Feature 23 · Visa", description: "The documents a German student-visa application needs, plus appointment lead times to plan around.", group: "visa", category: "visa", icon: ListChecks, featureNo: 23, disclaimer: true, Component: VisaChecklist },
  { path: "/visa/appointment", label: "Visa appointment tracker", title: "Visa appointment tracker", eyebrow: "G34 · Visa", description: "Mission appointment waits can run months. Track your booked slot and the document deadlines around it so the visa never becomes your bottleneck.", group: "visa", category: "visa", icon: CalendarDays, disclaimer: true, Component: VisaAppointment },
  { path: "/visa/visa-type", label: "Which visa do I need?", title: "Visa-type selector", eyebrow: "G36 · Visa", description: "Study visa, applicant visa, or language-course visa? Answer a couple of questions to find the right category for your situation.", group: "visa", category: "visa", icon: Plane, disclaimer: true, Component: VisaType },
  { path: "/visa/videx", label: "VIDEX form walkthrough", title: "VIDEX visa-form walkthrough", eyebrow: "G35 · Visa", description: "The online national-visa form (VIDEX) trips people up. Walk through what each section asks and the documents to have open while you fill it.", group: "visa", category: "visa", icon: FileText, disclaimer: true, Component: VisaVidex },
  { path: "/visa/aps", label: "APS guide", title: "APS certificate guide", eyebrow: "Feature 24 · Visa", description: "Understand the Akademische Prüfstelle check required for students from some countries, and how to get it.", group: "visa", category: "visa", icon: Stamp, featureNo: 24, disclaimer: true, Component: VisaAps },
  { path: "/visa/accommodation", label: "Accommodation finder", title: "Accommodation finder", eyebrow: "Feature 25 · Visa", description: "Find student housing — Studierendenwerk dorms and the private market — and avoid common rental scams.", group: "visa", category: "visa", icon: Building2, featureNo: 25, disclaimer: true, Component: VisaAccommodation },
  { path: "/visa/anmeldung", label: "Anmeldung simulation", title: "Anmeldung (address registration)", eyebrow: "Feature 26 · Visa", description: "Walk through registering your address at the Bürgeramt after you arrive — the step that unlocks everything else.", group: "visa", category: "visa", icon: MapPin, featureNo: 26, disclaimer: true, Component: VisaAnmeldung },
  { path: "/arrival", label: "Arrival overview", title: "Arrival & settling in", eyebrow: "Phase 8 · Arrival", description: "The steps nobody warns you about — the ones after you land. Register, open a bank account, convert your visa, enrol, and stay on top of renewals.", group: "arrival", icon: MapPin, Component: ArrivalOverview },
  { path: "/arrival/enrolment", label: "Enrolment (Immatrikulation)", title: "Enrolment (Immatrikulation) guide", eyebrow: "G27 · Arrival", description: "Turn your admission letter into a student place: the documents, the semester contribution, and the Matrikelnummer that unlocks campus life.", group: "arrival", icon: GraduationCap, Component: ArrivalEnrolment },
  { path: "/arrival/bank-account", label: "German bank account", title: "Opening a German bank account", eyebrow: "G38 · Arrival", description: "The account that unblocks your Sperrkonto payouts, rent, and salary — which type to open, what you need, and the order to do it in.", group: "arrival", icon: Landmark, Component: ArrivalBankAccount },
  { path: "/arrival/residence-permit", label: "Residence permit tracker", title: "Residence-permit (Aufenthaltstitel) conversion", eyebrow: "G39 · Arrival", description: "Your entry visa must become a residence permit at the Ausländerbehörde — track the documents, the appointment, and the deadline so it never lapses.", group: "arrival", icon: Stamp, disclaimer: true, Component: ArrivalResidencePermit },
  { path: "/arrival/auslaenderbehoerde", label: "Ausländerbehörde tracker", title: "Ausländerbehörde appointment & documents", eyebrow: "G40 · Arrival", description: "The foreigners' office runs your residence permit. Track your appointment and assemble the exact document set it expects.", group: "arrival", icon: Building2, disclaimer: true, Component: ArrivalAuslaenderbehoerde },
  { path: "/arrival/university-onboarding", label: "University onboarding", title: "First-weeks university onboarding", eyebrow: "G41 · Arrival", description: "Matrikelnummer, student ID & email, library and IT accounts, course registration, and the Rückmeldung you mustn't miss.", group: "arrival", icon: School, Component: ArrivalUniversityOnboarding },
  { path: "/arrival/anmeldung-runbook", label: "Anmeldung runbook", title: "Anmeldung — booking & document runbook", eyebrow: "G42 · Arrival", description: "A practical, city-agnostic runbook for booking the Bürgeramt appointment and bringing exactly the right documents the first time.", group: "arrival", icon: ClipboardList, Component: ArrivalAnmeldungRunbook },
  { path: "/arrival/rundfunkbeitrag", label: "Rundfunkbeitrag & utilities", title: "Rundfunkbeitrag & utilities setup", eyebrow: "G43 · Arrival", description: "The mandatory broadcasting fee per household, plus electricity, internet, and liability insurance — the bills that blindside new arrivals.", group: "arrival", icon: Coins, Component: ArrivalRundfunkbeitrag },
  { path: "/arrival/job-seeker-permit", label: "Post-study job-seeker permit", title: "18-month post-study job-seeker permit", eyebrow: "G44 · Ongoing", description: "After graduation you can stay up to 18 months to find qualified work — what it allows, when to apply, and the path to a work permit or Blue Card.", group: "arrival", icon: Briefcase, disclaimer: true, Component: ArrivalJobSeekerPermit },
  { path: "/arrival/family-reunion", label: "Family reunion", title: "Bringing your family (Familiennachzug)", eyebrow: "G45 · Ongoing", description: "If a spouse or children join you, plan the family-reunion visa: who qualifies, the income and housing expectations, and the documents.", group: "arrival", icon: Users, disclaimer: true, Component: ArrivalFamilyReunion },
  { path: "/arrival/renewals", label: "Renewals & re-registration", title: "Permit renewals & semester re-registration", eyebrow: "G46 · G47 · Ongoing", description: "Two recurring deadlines that get people exmatrikuliert or out of status: residence-permit renewal and the semester Rückmeldung. Set them and never miss them.", group: "arrival", icon: BellRing, Component: ArrivalRenewals },
  { path: "/arrival/arrival-day", label: "Arrival-day planner", title: "Arrival-day & first-72-hours planner", eyebrow: "G37 · Arrival", description: "A practical sequence for landing day and the first few days: SIM, transport, temporary stay, cash, and the appointments to book immediately.", group: "arrival", icon: Backpack, Component: ArrivalArrivalDay },
  { path: "/arrival/blue-card", label: "Blue Card & settlement", title: "EU Blue Card & permanent settlement", eyebrow: "G48 · Ongoing", description: "The work-to-settlement endgame: how a qualified job becomes an EU Blue Card and, in time, permanent residence (Niederlassungserlaubnis).", group: "arrival", icon: Award, disclaimer: true, Component: ArrivalBlueCard },
  { path: "/arrival/immigration-pathway", label: "Your immigration long-game", title: "Study → Blue Card → PR → Citizenship", eyebrow: "Long game · Ongoing", description: "The full ladder from student to citizen, personalised to your field and German level — with the current 2026 thresholds, timelines, and the official sources to verify each.", group: "arrival", icon: Route, disclaimer: true, Component: ArrivalImmigrationPathway },
  { path: "/arrival/blue-card-check", label: "Blue Card salary check", title: "EU Blue Card eligibility check", eyebrow: "Long game · Tool", description: "Enter an expected salary and field to see whether it clears the 2026 Blue Card threshold — the lower one for shortage occupations, STEM, and recent graduates.", group: "arrival", icon: Gauge, disclaimer: true, Component: ArrivalBlueCardCheck },
  { path: "/arrival/pr-citizenship", label: "PR & citizenship timeline", title: "PR & citizenship timeline tracker", eyebrow: "Long game · Tool", description: "Track your qualified-residence start and German level to see indicative dates for permanent residence and citizenship under the current 2026 rules.", group: "arrival", icon: Stamp, disclaimer: true, Component: ArrivalPrCitizenship },
  { path: "/arrival/tax-id", label: "Tax-ID & first job", title: "Tax-ID & first-job onboarding", eyebrow: "G49 · Ongoing", description: "Starting work means a tax ID, a tax class, social contributions, and the Werkstudent rules. Here's what to set up and what to expect on your payslip.", group: "arrival", icon: FileBadge, disclaimer: true, Component: ArrivalTaxId },
  { path: "/campus", label: "Overview", title: "Campus Life", eyebrow: "Bereich F · Campus Life", description: "Land well: pre-departure packing, academic networking, transit, and how German academic culture works.", group: "campus", category: "campus", icon: Sparkles, Component: CampusOverview },
  { path: "/campus/pre-departure", label: "Pre-departure checklist", title: "Pre-departure checklist", eyebrow: "Feature 27 · Campus", description: "Everything to arrange and pack before you fly — documents, money, tech, and first-week essentials.", group: "campus", category: "campus", icon: Backpack, featureNo: 27, Component: CampusPreDeparture },
  { path: "/campus/networking", label: "Academic networking", title: "Academic networking", eyebrow: "Feature 28 · Campus", description: "Build relationships with professors, peers, and student groups — how to reach out and what to say.", group: "campus", category: "campus", icon: Users, featureNo: 28, Component: CampusNetworking },
  { path: "/campus/deutschlandticket", label: "Deutschlandticket guide", title: "Deutschlandticket guide", eyebrow: "Feature 29 · Campus", description: "Use Germany's nationwide public-transport ticket and the discounted student semester ticket.", group: "campus", category: "campus", icon: TramFront, featureNo: 29, Component: CampusDeutschlandticket },
  { path: "/campus/culture", label: "Academic culture", title: "Academic culture & plagiarism", eyebrow: "Feature 30 · Campus", description: "How German universities expect you to study, cite, and behave — including strict plagiarism rules.", group: "campus", category: "campus", icon: BookOpen, featureNo: 30, Component: CampusCulture },
  { path: "/about", label: "About & methodology", title: "About DeutschPrep", eyebrow: "Info · Methodik", description: "How DeutschPrep grounds official facts, computes deterministic values, and what it does not do.", group: "system", icon: Info, Component: AboutPage },
  { path: "/settings", label: "Profile & settings", title: "Profile & settings", eyebrow: "Einstellungen · Settings", description: "Manage the intake details that personalize your roadmap. Your data stays on this device in this build.", group: "system", icon: Settings, Component: SettingsPage },
  { path: "/help", label: "Help & FAQ", title: "Help & FAQ", eyebrow: "Hilfe · Help", description: "Answers to common questions, with the advisory disclaimer and links to official sources.", group: "system", icon: CircleHelp, Component: HelpPage },
  { path: "/legal/privacy", label: "Privacy Policy", title: "Privacy Policy", eyebrow: "Datenschutz · Privacy", description: "How DeutschPrep handles your personal data, including GDPR export and deletion.", group: "system", icon: ShieldCheck, hide: true, Component: PrivacyPage },
  { path: "/legal/terms", label: "Terms of Service", title: "Terms of Service", eyebrow: "Nutzungsbedingungen · Terms", description: "The terms for using DeutschPrep.", group: "system", icon: FileText, hide: true, Component: TermsPage },
  { path: "/legal/accessibility", label: "Accessibility", title: "Accessibility statement", eyebrow: "Barrierefreiheit · Accessibility", description: "Our commitment to WCAG 2.1 AA and how to report barriers.", group: "system", icon: Accessibility, hide: true, Component: AccessibilityPage },
  { path: "*", label: "Not found", title: "Page not found", eyebrow: "404", description: "That page doesn't exist. Use the navigation to get back on track.", group: "system", icon: FileSearch, hide: true, Component: NotFoundPage },
];

/** Visible nav items grouped in sidebar order. */
export function navByGroup(): { key: NavGroupKey; label: string; items: NavItem[] }[] {
  return (Object.keys(NAV_GROUPS) as NavGroupKey[]).map((key) => ({
    key,
    label: NAV_GROUPS[key],
    items: NAV.filter((n) => n.group === key && !n.hide),
  })).filter((g) => g.items.length > 0);
}

/** Look up a nav item by exact path. */
export function navItem(path: string): NavItem | undefined {
  return NAV.find((n) => n.path === path);
}
